### ISSUE TITLE
No IntelliSense?

### ISSUE THREAD

**Issue by prashaantt** [flowtype/flow-for-vscode#10]
On the latest VSCode I don't get IntelliSense or peek support, just hinting. Is something broken with Code or this plugin?

**Comment by Dharmoslap** [comment]
Move to TypeScript 😄

**Comment by prashaantt** [comment]
@Dharmoslap That's exactly what I did after struggling with this plugin. TypeScript is amazing and I couldn't be happier.

**Comment by bochen2014** [comment]
hahaha

I love typescript as well and unfortunately those fb guys think flow is better ...
when you deal with a project that was written in flow+es6, it's just  so painful to code without intellisense..
