### ISSUE TITLE
Maybe type not parsed correctly

### ISSUE THREAD

**Issue by petrbela** [flowtype/flow-for-vscode#101]
The `maybe` type, when defined as `?string`, doesn't seem to be parsed correctly, resulting in weird error messages:

![screen shot 2017-03-29 at 3 02 50 pm](https://cloud.githubusercontent.com/assets/668124/24458462/e66fe310-1490-11e7-8ff5-9b0eaa9326ab.png)

Interestingly enough, if I use an optional variable as:

```js
type Props = {
  placeholder?: string,
  onSubmit: (text: string) => void,
}
```

then it works correctly.

`flow` run from command line works correctly in both cases.

**Comment by orta** [comment]
could be a difference between global flow and local flow?

**Comment by Mayank1791989** [comment]
The error is correct. In ```type Props = { placeholder?: string };``` `placeholder` is optional and if passed it should be string while in `type Props = { placeholder: ?string }` `placeholder` is required and it accepts `undefined|null|string`.
