### ISSUE TITLE
Type cast expression in string template breaks syntax highlighting

### ISSUE THREAD

**Issue by siegebell** [flowtype/flow-for-vscode#103]
vscode 1.10.2
OS: Mac 10.12.3

In the following example, syntax highlighting breaks at the first '}'. When there is a subsequent expression after the type cast (e.g. `${2}`), it breaks highlighting for the rest of the file.
```typescript
const x = 0;
const y = `${(x: number)} highlighting is broken here ${2}`;
const z = 'syntax highlighting is broken to the end of the file';
```

![screen shot 2017-04-03 at 3 12 07 pm](https://cloud.githubusercontent.com/assets/16118166/24633914/fb087f7e-187f-11e7-81ea-5ebd3212fb09.png)

See also: #34 #93 

This kills the readability of flow programs and I pretty much have to turn syntax highlighting off altogether. In my opinion, either the flow grammar should be resurrected or else the typescript grammar needs to be tweaked to not completely break down in this situation.

**Comment by orta** [comment]
If you're willing to create, *maintain* and set up a Flow tmlanguage for this extension then I'm alright with shipping one. It was done before and removed for being really tough to keep up to date, and support all the vscode features.

IMO it might be better to send a PR to the official JS one to make it not break in cases like this though.

**Comment by siegebell** [comment]
This issue appears to be fixed my installing extension ms-vscode.js-atom-grammar, which uses Atom's javascript grammar. Maybe update the documentation to suggest installing this extension?

**Comment by orta** [comment]
Rockin' thanks @siegebell - I've shipped a README fix

**Comment by yenbekbay** [comment]
Another option is to use https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode, which IMO provides better syntax highlighting.

**Comment by Mayank1791989** [comment]
This plugin doesn't provide syntax highlighting. Use https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel for that.
