### ISSUE TITLE
"Unexpected Token" for Exact Object Type

### ISSUE THREAD

**Issue by habibialkaff** [flowtype/flow-for-vscode#107]
There's an error showing when I try to use exact object type

<img width="339" alt="screen shot 2017-04-09 at 05 45 08" src="https://cloud.githubusercontent.com/assets/1284550/24833048/2df69a80-1ce8-11e7-8bf0-c75d13995244.png">

When I run the flow-cli from command line, it says "No errors"

**Comment by habibialkaff** [comment]
and when I use $Exact (https://flow.org/en/docs/types/utilities/#toc-exact) , it throws another error

<img width="554" alt="screen shot 2017-04-09 at 10 30 34" src="https://cloud.githubusercontent.com/assets/1284550/24834450/be6a6660-1d0f-11e7-993c-0473f85518c1.png">

**Comment by orta** [comment]
Could this be a global vs local flow issue?

**Comment by habibialkaff** [comment]
Interesting! I have the above errors when I use the global one. When I switch to local, the error disappears and the exact object type works as expected

**Comment by thymikee** [comment]
@habibialkaff FWIW new syntax for exact object was introduced in [0.32](https://github.com/facebook/flow/blob/master/Changelog.md#v0320) so be sure to check that.

**Comment by Mayank1791989** [comment]
Try using some latest flow. It will work.
