### ISSUE TITLE
Flow checks for CSS files?

### ISSUE THREAD

**Issue by svipben** [flowtype/flow-for-vscode#115]
Hello,

Flow type coverage is checking also for CSS files which is bad. I think you need to include ONLY `.js` files. As you can see in picture I opened `app.css` file and I get `Flow type coverage` and by pressing it I get warnings (green lines below) which says which code is uncovered...

![screenshot from 2017-04-22 11-25-02](https://cloud.githubusercontent.com/assets/10441177/25302773/cc0c6c48-274e-11e7-9b35-c36cb0145026.png)

P.S. Same happens to JSON files... It seems it checks for ALL files, not only JS.

**Comment by orta** [comment]
I think this could be that the extension isn't hiding the information when you're not on a `javascript` / `javascriptreact` file, wanna try fixing that?

**Comment by svipben** [comment]
@orta Never tried to work on VS Code plugins, don't even know how to correctly work on it :smile:

**Comment by orta** [comment]
Neither did I until I decided to make some improvements to this, there's a bunch of info in the readme. 👍

**Comment by svipben** [comment]
@orta Sorry no time, need to make bachelor's work...

**Comment by infinityfarm** [comment]
@orta I might be interested in taking a crack at this tomorrow.. any tips/context appreciated

**Comment by orta** [comment]
Maybe finding out when the editor document has changed, then checking if it's a js/jsx file and removing the bottom decoration if it's not

**Comment by thymikee** [comment]
Addressed PR for that

**Comment by svipben** [comment]
@thymikee Very good!
