### ISSUE TITLE
Flow works even if I don't use flow annotation

### ISSUE THREAD

**Issue by svipben** [flowtype/flow-for-vscode#116]
Hello,

Flow is working even if I'm don't using `// @flow` annotation... 

![screenshot from 2017-04-22 13-25-13](https://cloud.githubusercontent.com/assets/10441177/25303599/56d2a7a6-275f-11e7-9c69-99c28b257dbd.png)

![screenshot from 2017-04-22 13-25-32](https://cloud.githubusercontent.com/assets/10441177/25303600/584e4c7a-275f-11e7-8aee-4e18b9ce605d.png)

When I delete that `a;` and save, errors disappears. And this happens for all `.js` documents, by the way the funniest part is, in `[ignore]` is this `__tests__` dir, there's this file `app.test.js`, but I even tested with other `.js` files it's the same... So this plugin somehow ignores even `[ignore]` in `.flowconfig` and you don't need type `// @flow` or `/* @flow */` to enable type check, funny :smile:

**Comment by svipben** [comment]
Also right now VS Code started to lag more, I think it's related...

**Comment by AbsoluteZero273** [comment]
I've started to feel the lag too.

**Comment by patrickgordon** [comment]
I have the same issue. Extension is version 0.6.0

**Comment by svipben** [comment]
@patrickgordon Did you feel lag too?

**Comment by patrickgordon** [comment]
@svipben yes lagging a lot

**Comment by minedeljkovic** [comment]
Reason for lagging might be new "run on edit" feature.
You can turn it off in your vscode settings. [See here](https://github.com/flowtype/flow-for-vscode/blob/12c900ec53aa357a6a63f5d3b1c1224b86def89b/README.md#configuration)

**Comment by AbsoluteZero273** [comment]
@minedeljkovic Thanks! Yeah, "run on edit" was the problem for lag. But the plugin stills checks files without flow annotation.

**Comment by svipben** [comment]
@minedeljkovic I will try that, but I think they are related, also not lag is the problem, but Flow check works even if there's no `// @flow` annotation, so there's 2 problems, lagging and checking without `// @flow` annotation. By the way, if this rule causing some lag, why it's turned true by default? :smile:

**Comment by AbsoluteZero273** [comment]
Yeah, "run on edit" should be turned off by default or should be debounced.

**Comment by svipben** [comment]
@AbsoluteZero273 I agree 100%.

**Comment by svipben** [comment]
Memory and process usage is really huge, I hear how my laptop fan is working very fast :smile: Better really make that run on edit off by default or fix it, if it has problems.

**Comment by orta** [comment]
Sounds reasonable, someone want to send a PR?

**Comment by AbsoluteZero273** [comment]
@orta PR to disable it by default or something more?

**Comment by svipben** [comment]
@AbsoluteZero273 I think he's talking about whole problem related with this option (run on edit) and by flow working even if there's no annotation. Because to disable run on edit by default it's pretty easy, just edit package.json file :smile:

**Comment by orta** [comment]
I've shipped the package.json change in #120

**Comment by thymikee** [comment]
PR addressed

**Comment by svipben** [comment]
@thymikee Nice!
