### ISSUE TITLE
Upgrading underlying Flow interaction code

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-for-vscode#12]
We depend on the `nuclide-flow-base` npm package to manage interactions with Flow. Unfortunately for this project, Nuclide has undergone a restructuring that puts everything in a single package.

The Nuclide team has explored options that would allow `flow-for-vscode` to consume just the Flow parts of the Nuclide code but we have concluded that splitting it off entirely would be prohibitively expensive. So, for this project we have a few options:
- Give up on maintaining it :disappointed:. However since we only have 400 and change downloads it might make sense.
- Consume the entire `nuclide` package and just reach in to use the Flow bits. I haven't looked into this option extensively but I'm pretty sure we can make it happen, although it would be a bit hacky. The main issue is that it would balloon the installed size of this package to somewhere around 100-150 MB.
- Fork Nuclide's Flow code by copying it in to this repository and carving out the dependencies it has on Nuclide's other code. Doing so would make it painful to pull in new versions, but maybe that's okay. From here we could either just maintain a fork or still try to pull in new versions of Nuclide's code.

Thoughts on this or other ideas are welcome.

**Comment by bpasero** [comment]
Ouch, none of them sound very compelling :). How bad is option 3? is it a full clone of everything from the point before the single package happened?

**Comment by nmote** [comment]
For option 3 I imagine we will just copy and paste the relevant files and then remove the bits that depend on other Nuclide code (won't be too hard). So, not a fork in the GitHub sense with preserved history and all that.

I guess option 4 is just to start from scratch, but I don't have the time or motivation for that and I don't see why we wouldn't at the very least just copy and modify what Nuclide already has.

**Comment by bpasero** [comment]
Right, option 3 seems like the best option for now then.

**Comment by nmote** [comment]
Sounds good. This week I'll fix #9 in the Nuclide code and then let's fork it after that.

**Comment by bpasero** [comment]
Nice :+1:

**Comment by rtorr** [comment]
Could you not fork and then publish https://github.com/facebook/nuclide/tree/master/pkg/nuclide-flow-base under a new namespace? I know kind of a pain, but might work.

**Comment by nmote** [comment]
It's certainly possible, but I don't intend to spend time on that, at least in the foreseeable future.

**Comment by rtorr** [comment]
I am currently working on an extension without a dependency on nuclide code at all. https://vid.me/1Y62

**Comment by rtorr** [comment]
The repo is here https://github.com/rtorr/vscode-flow. I have declaration and diagnostic support working, Completion seems to just use vscode's built in completion. Published with Facebook's license since I referenced this code/reused what I could. Still need to make it more "production" ready though.

On the marketplace as `vscode-flow`.

**Comment by orta** [comment]
Alright, I think this can be closed #19 re-integrated all of the JS from nuclide 👍
