### ISSUE TITLE
Non nullable types produce additional parameters in Visual Studio Code Intellisense.

### ISSUE THREAD

**Issue by Stralos** [flowtype/flow-for-vscode#125]
If functions have flows <a href="https://flow.org/en/docs/types/maybe/">maybe types </a> they produce an additional parameter inside visual studios intelisence compared with normal (not nullable types)

picture example:
Produces additional function parameter:
<img width="1433" alt="screen shot 2017-05-07 at 01 12 26" src="https://cloud.githubusercontent.com/assets/9497563/25776289/15928792-32c3-11e7-9a25-d8e4be429679.png">

Does not produce:
<img width="1431" alt="screen shot 2017-05-07 at 01 14 02" src="https://cloud.githubusercontent.com/assets/9497563/25776296/2938a380-32c3-11e7-8f7c-a6e7ad150e3f.png">

**Comment by Mayank1791989** [comment]
Flow doesn't support signature-help. Looks like it's coming from typescript plugin. Anyways I tried locally with typescript plugin enabled but it's not happening may be some old issue in typescript plugin.
