### ISSUE TITLE
SUGGESTION: make types in comments colorized

### ISSUE THREAD

**Issue by svipas** [flowtype/flow-for-vscode#128]
Hello,

my suggestion is to make types in comments colorized like it's in Atom. This will be really cool to have in VS Code. The color of types will be as it is right now if we write it outside of comments.

VS Code:

![screenshot from 2017-04-29 18-20-33](https://cloud.githubusercontent.com/assets/10441177/25556654/d7194524-2d08-11e7-83f6-341498c91b1c.png)

Atom:
![screenshot from 2017-04-29 18-20-54](https://cloud.githubusercontent.com/assets/10441177/25556657/ded6b92c-2d08-11e7-9019-1bd34ddf06b6.png)

As you can see in Atom it is colorized like it was outside of comments, it will be very cool to have it same in the VS Code.

Flow supports types, classes, interfaces and so on in comments, here is doc https://flow.org/en/docs/types/comments/.

**Comment by svipben** [comment]
In Atom editor colored comments is with https://github.com/gandm/language-babel plugin.

**Comment by Mayank1791989** [comment]
See https://github.com/flowtype/flow-for-vscode#known-issues
