### ISSUE TITLE
Make use of ./node_modules/.bin/flow instead of ./node_modules/flow-bin/

### ISSUE THREAD

**Issue by saitonakamura** [flowtype/flow-for-vscode#129]
Is there any particular reason for using flow binary from `./node_modules/flow-bin/` (`./node_modules/flow-bin/flow-win64-v0.44.2/flow` in my case)?
It leads to the problem that you can't use `yarn run flow` or `npm run flow`, I get
```
flow is running on a different directory.
server_root: c:\Users\saito\code\webtasks\WebTasksApp, client_root: C:\Users\saito\code\webtasks\WebTasksApp
Unhandled exception: CommandExceptions.Server_directory_mismatch
```
I can workaround it by explicitly running flow from `flow-bin`, but some other packages, e.g. `flow-coverage-report`, uses flow from `.bin` and I can't change that

**Comment by fqborges** [comment]
Same here.
Did you dig into the problem? It seems to be something just related to the case in windows drive letter.

**Comment by orta** [comment]
You're welcome to send a PR adding this 👍 

I added it this way because it worked fine for my setup on macOS

**Comment by saitonakamura** [comment]
Can you show me where to dig? I've already tried to fix by playing with source code it but no luck.

**Comment by saitonakamura** [comment]
Let's close it as stale
