### ISSUE TITLE
Usage with node_modules not in project root

### ISSUE THREAD

**Issue by maxekman** [flowtype/flow-for-vscode#130]
With the `flow.useNPMPackagedFlow` option and the node_modules folder in a subfolder of the project root I can't get it to find the flow binary. Looking at the source of the extension it looks like it will only try to find the node_modules folder in the project root, which is problematic in our case as the frontend is one folder of many in a larger project.

Any suggestions for how to use the flow extension with this setup (without installing flow globally)? I suppose a workspace for the subfolder with the frontend could work, but ideally I would like to have only one project.

**Comment by orta** [comment]
The next release will ship Flow with the extension, which should simplify this 👍

**Comment by maxekman** [comment]
Sounds good!

You can decide if you want to close this or not. I think (but have not confirmed) that it can't find the .flowconfig in a sub folder either.

**Comment by ubershmekel** [comment]
@orta how will shipping the flow extension solve this problem? How can I be sure that everyone on my team is using the same flow-bin if they're not all on vscode and on the same extension version? I guess if you detected the `.flowconfig` roots then potentially running multiple versions of the flow server might give rise to other issues for you guys.

@maxekman I also have many projects in my one github repository which brought me to this issue. At the moment my workaround is to install one flow-bin at the root which will be shared by all the projects as far as vscode is concerned. Just run `yarn add flow-bin` at the root of your workspace.

For reference, flow-for-vscode is relying on the root of the vscode workspace to have a `node_modules` folder with the flow binary.

https://github.com/flowtype/flow-for-vscode/blob/728aa73a6f8a088517d6ba1e3bd213f2e797ac29/lib/pkg/flow-base/lib/FlowHelpers.js#L170

```
    const nodeModuleFlowPath = nodeModuleFlowLocation(global.vscode.workspace.rootPath)
    `${rootPath}/node_modules/.bin/flow`
```

**Comment by orta** [comment]
It doesn't help that, you're welcome to send a PR implementing a setting for something like this though 👍

**Comment by amosyuen** [comment]
Looks like submitted https://github.com/flowtype/flow-for-vscode/commit/80b5cd1b1036036315b1a88991c043fcf5bbfffe which should allow users to replace ${workspaceRoot} in the path.

Any idea when a new version is getting released?

**Comment by Mayank1791989** [comment]
Fixed in https://github.com/flowtype/flow-for-vscode/pull/315. Try v1.1.0.
