### ISSUE TITLE
Diagnostics will not work with Flow v0.23

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-for-vscode#14]
Flow v0.23 changes the JSON format used for diagnostics, which will cause this package to be unable to display them correctly.

**Comment by frogcjn** [comment]
How to use flow 0.25 with VSCode extension? Is it broken?

**Comment by nmote** [comment]
Unfortunately yes. I don't currently have the time to maintain this plugin, though I will happily review pull requests. A solution to #12 will resolve this, since Nuclide has been updated to support the newer Flow versions.

**Comment by frogcjn** [comment]
See https://github.com/flowtype/flow-for-vscode/pull/15

**Comment by orta** [comment]
Fixed in #15 I believe.
