### ISSUE TITLE
unexpected global variables seen in intellisense

### ISSUE THREAD

**Issue by bochen2014** [flowtype/flow-for-vscode#140]
it's almost perfect except unexpected global variables been displayed ... 
![image](https://user-images.githubusercontent.com/8207081/26862308-86b6199c-4b8d-11e7-818c-72b73f2e55d5.png)

any idea?

**Comment by bochen2014** [comment]
sorry... scopped variables are displayed as well.. which is a big problem...

![image](https://user-images.githubusercontent.com/8207081/26862478-e54a8c1c-4b8e-11e7-8555-b8c8f32219d8.png)

**Comment by orta** [comment]
This is a feature of VS Code, you can turn it off via `"javascript.nameSuggestions": false,`
