### ISSUE TITLE
Multiple flows?

### ISSUE THREAD

**Issue by proProbe** [flowtype/flow-for-vscode#142]
Hello everyone!

I recently got a somewhat weird flow bug where vscode shows definition from two different flows? One which is [flow] and one with [Flow]. Im attaching a gif that showcases this. It is possible that my configurations are wack but I am not sure whats causing this so Im writing here.

![test](https://user-images.githubusercontent.com/3802899/27451043-1b198e0a-578e-11e7-8466-124c2ead22b3.gif)

**Comment by orta** [comment]
Could this be two different extensions?

**Comment by proProbe** [comment]
Im currently only seeing one which is the *flow-for-vscode*-extension :/ no one else has this problem?

**Comment by julienvincent** [comment]
I also get this with only flow-for-vscode installed

**Comment by ksmth** [comment]
I'm having the exact same issue ... it's quite infuriating, because one usually shows an error, while the other is able to show the proper type, exactly as shown in the gif

**Comment by Mayank1791989** [comment]
Not happening with latest version of plugin. Maybe some old issue which is already fixed. Also make sure you are not using two flow plugins.
