### ISSUE TITLE
If Set nodeModuleFlowLocation, should locate flow bin relative to the .flowconfig

### ISSUE THREAD

**Issue by imlgm** [flowtype/flow-for-vscode#143]
I have more than one project, all of them was put in to a projects folder, I'like open the projects folder so I can switch between project without having to  switch windows. 

Here is a problem, if I open a project using flow as the root dir, no error popup.
but if i open the projects folder contains all the project, there will be an error tell me flow bin can not be found. 

so I guess, if I set nodeModuleFlowLocation to true,  the extentions will look for flow-bin by the opened directory root, not the project folder which contains .flowconfig

**Comment by Mayank1791989** [comment]
fixed in b5be6578a7a51dfb4e38db4c2f1a1ad41c3afb82. Try v1.1.0.
