### ISSUE TITLE
Hover on "import" line shows as "any"

### ISSUE THREAD

**Issue by Noitidart** [flowtype/flow-for-vscode#146]
Whenever I import anything from a module, hovering over it always shows it as `any`. And the flow highlight syntax treats it as any.

Screenshots:

* we see on hover `FontWeight` is shown as `any`:
    ![](http://i.imgur.com/bTuSsbZ.png)
* we see here that `FontWeight` is not defined as `any`:
    ![](http://i.imgur.com/svuDGiA.png)

**Comment by Noitidart** [comment]
Here is steps to reproduce for another example:

1. react-native init blah
2. add file to root `types.js` with:
    ```
    type Rawr = number;
    export type { Rawr }
    ```

3. In `index.ios.js` do:
    ```
    import type { Rawr } from './types'
    const blah: Rawr = 'rawaa';
    ```

Screenshots:
types.js - http://i.imgur.com/ZdRvIbR.png
index.ios.js - http://i.imgur.com/msMY3g6.png
(notice in index.ios.js screenshot in bottom left Flow: 100.0% and no error highlighting)

i have flow-bin installed globally at 0.47 and it matches that found in my projects `.flowconfig`

**Comment by orta** [comment]
I'm reasonably sure that what you're seeing here is the VS Code TypeScript inferred types- Flow messages have the prefix "Flow: "

**Comment by Noitidart** [comment]
@orta Oh you are totally right!!

So the types are working right. Its just the hover on the import is showing incorrect:

Hover of import is showing typescript:

![](http://i.imgur.com/Wkcm0fj.png)

But hover over the used type after import is showing correct:

![](http://i.imgur.com/AG8PxJ8.png)

**Comment by DarrylD** [comment]
I've been having the same issue for quite some time. @Noitidart have you found a solution? Flow is not nearly as useful with this issue.

**Comment by Noitidart** [comment]
@DarrylD I found no solution. I can only just use the import then hover to see if it is correct.

**Comment by liushigit** [comment]
Same here: https://github.com/flowtype/flow-for-vscode/issues/23#issuecomment-325130856

**Comment by johot** [comment]
Same problem for me. Created a new react app using `create-react-app` installed flow and the addon to vs code. Always shows `any` for me when doing `import type`.

**Comment by joshyhargreaves** [comment]
@Noitidart, I think it's not a case of hover showing the 'wrong' type information, it should show both sets of type information (as you can't currently turn the typescript hover type info off in code). 

I'm seeing something similar whereby `flow-for-vscode` doesn't show type information for even a locally declared type. 
![image](https://user-images.githubusercontent.com/1807207/30476078-ce722c0a-9a00-11e7-9396-aaefa84f0e09.png)

**Comment by fpersico** [comment]
The problem is that the plugin can't get the real type if you write import like this
`import type { ApplicationActions } from "./application";`

try with

import { type ApplicationActions } from "./application";

**Comment by rihdus** [comment]
Having a similar issue.
This does not recognise the type import
```js
import type { ProfileConfig } from './ProfileConfig';
```
This does.
```js
import { type ProfileConfig } from './ProfileConfig';
```

**Comment by Tasemu** [comment]
Can we get hover support for

`import type { ProfileConfig } from './ProfileConfig';`

Otherwise we have babel trying to do a lot for nothing on our CRA app.

**Comment by jcrjaci** [comment]
I got the same problem.

![image](https://user-images.githubusercontent.com/3009975/49974671-4cfe9300-ff32-11e8-8b5b-581bd380eb8e.png)

1º problem:
If I hovered the import types, always display type any as shown in the picture above.
2º problem:
As displayed in line number 25 in the left file you'll see:
`case 'asd':`
The type 'asd' is not defined in the action type and should catch the error.
If I place the types in the same file and not import them it works as expected.

**Comment by jcrjaci** [comment]
> I got the same problem.
> 
> ![image](https://user-images.githubusercontent.com/3009975/49974671-4cfe9300-ff32-11e8-8b5b-581bd380eb8e.png)
> 
> 1º problem:
> If I hovered the import types, always display type any as shown in the picture above.
> 2º problem:
> As displayed in line number 25 in the left file you'll see:
> `case 'asd':`
> The type 'asd' is not defined in the action type and should catch the error.
> If I place the types in the same file and not import them it works as expected.

Just figure out that I misspelled the @flow initial comment in the types.js file. I had a space between @ and flow.

**Comment by Mayank1791989** [comment]
Try using latest flow version. Hover working fine with it.

**Comment by FullstackJack** [comment]
How do we reopen this issue. We are using latest 0.102.0 and it's not fixed.

**Comment by FullstackJack** [comment]
Nevermind, was exporting from an `index.js` and the `index.js` was missing `// @flow`.
