### ISSUE TITLE
flow error on vscode sometimes shows the wrong file name but flow status is good

### ISSUE THREAD

**Issue by rvion** [flowtype/flow-for-vscode#154]
## flow error on vscode sometimes shows the wrong file info but flow status is good

![image](https://user-images.githubusercontent.com/2150990/29239061-702a35ba-7f44-11e7-9297-100219a8d120.png)

📙 mention `link.js`file but `link.js` is only the file containing the type declaration, not the place where we need to fix the error

## `flow status` shows the correct file (option.js, the file that use Link) where we need to fix the error before the link.js file

`show status`:

```
Error: src/components/option.js:20
 20:           <Link  className="btn" action={actions.goToAddOption({problem_id: 1})}>✚</Link>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Link`
 41: export const Link : ConnectedComponentClass<OP, P, void, void> = connect()(Link1);
                                                 ^^ property `title`. Property not found in. 
                                                 See: src/components/link.js:41
 20:           <Link  className="btn" action={actions.goToAddOption({problem_id: 1})}>✚</Link>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Link`
```

**Comment by Mayank1791989** [comment]
duplicate https://github.com/flowtype/flow-for-vscode/issues/122
