### ISSUE TITLE
Hover over object property shows incorrect type

### ISSUE THREAD

**Issue by sessio** [flowtype/flow-for-vscode#155]
When hovering over an object property, the popup suggests that property type would be the parent object type, this is pretty confusing at times.

![flow-hover](https://user-images.githubusercontent.com/1036372/29354726-049f2054-8277-11e7-86a0-eecd0f5e4382.png)

In the screenshot, i'm hovering over the 'b' property. Shouldn't the `[Flow]` portion of popup also say `b: string` instead of `b: { ... }`?

VS 1.15.0
flowtype 0.7.1

**Comment by orta** [comment]
We can't disable the top one, it comes from VS Code's TypeScript alas.

**Comment by sessio** [comment]
I'm saying the bottom portion seems to be wrong, not that top portion is extraneous
