### ISSUE TITLE
Flow not re-scaning on file change, only re-focus

### ISSUE THREAD

**Issue by zyklus** [flowtype/flow-for-vscode#157]
When I edit, or even save a file flow doesn't immediately re-scan.  It only seems to re-scan when I change focus to another file and then back.

What I mean is that the visible errors in the file don't change even if I introduce new ones / fix old ones.

**Comment by tharakawj** [comment]
I have the same issue and it's really annolying. I'm using latest 0.7.1 with vscode 1.15.
