### ISSUE TITLE
Feature Request: Find all References, Rename Symbol

### ISSUE THREAD

**Issue by rattrayalex-stripe** [flowtype/flow-for-vscode#160]
VSCode has support for "Find All References", but it does not appear to be implemented by this plugin. 

The same is true for Rename Symbol.

![screen shot 2017-09-05 at 1 33 25 pm](https://user-images.githubusercontent.com/29717832/30082215-df6e55fc-923e-11e7-9676-a6e35ba21014.png)

Features like this make refactoring a large codebase much easier, and are a commonly-mentioned draw to TypeScript. 

cc @danwang-stripe

**Comment by orta** [comment]
This can probably be done easier with https://github.com/flowtype/flow-for-vscode/issues/148 - it might be worth helping out on https://github.com/flowtype/flow-for-vscode/pull/150 to get it shippable

**Comment by rattrayalex-stripe** [comment]
Awesome, I'll see if I can carve out time to help (not likely in the short term). Hopefully that PR, or a follow-on, will close this issue. If not, it should at least make it easier for someone else to do so!

**Comment by rattrayalex-stripe** [comment]
@orta any word on this, now that #150 has been out for a little while?

**Comment by Mayank1791989** [comment]
Try plugin v1.1.0 find all references and rename symbol will work.
