### ISSUE TITLE
exact object type sytax highlighting issue

### ISSUE THREAD

**Issue by adambene** [flowtype/flow-for-vscode#162]
- flow-for-vscode@0.7.1
- VSCode@ Version 1.16.1 (1.16.1)

Syntax highlighting goes wrong after using the [exact object type syntax](https://flow.org/en/docs/types/objects/#toc-exact-object-types).
See attached screeenshot.
<img width="462" alt="screen shot 2017-09-16 at 12 50 25" src="https://user-images.githubusercontent.com/2473851/30511642-0e891442-9ade-11e7-8978-8d49e9109cbe.png">

**Comment by adambene** [comment]
bump

**Comment by denizdogan** [comment]
I have the same problem. Since exact object types are so common in Flow, I'd expect to see more noise about this one!

**Comment by orta** [comment]
I'm afraid the answer is the same as https://github.com/flowtype/flow-for-vscode/issues/93#issuecomment-288016021

**Comment by denizdogan** [comment]
@orta Thanks for your response. As I understand it, there's a significant amount of work required to make Flow for VSCode correctly parse Flow-annotated JavaScript? Are there any other VSCode extensions for VSCode which parses JS+Flow properly today?

**Comment by orta** [comment]
It's just that someone needs to build a flow syntax file, I have no idea if anyone has built one - you're welcome to have a look and report back 👍

**Comment by Mayank1791989** [comment]
see https://github.com/flowtype/flow-for-vscode#known-issues
