### ISSUE TITLE
flow consumes all ram

### ISSUE THREAD

**Issue by barbalex** [flowtype/flow-for-vscode#164]
I have described this in these comments:

- https://github.com/facebook/flow/issues/2152#issuecomment-333402410
- https://github.com/facebook/flow/issues/2152#issuecomment-333601924 (and two following)

The weird part is that it completely bombs out my pc when using vscode and flow-for-vscode. But when I use atom, there are no problems.

Could it be that flow-for-vscode is doing something unexpected?

**Comment by orta** [comment]
i bet the atom version uses flow-language-server: https://github.com/flowtype/flow-for-vscode/pull/150 and so has no need to spawn off the processes itself. You're welcome to try wrap up that PR for this extension.

**Comment by barbalex** [comment]
Thanks for the pointer. I think I'd bite off a bit too much...

**Comment by CharlesStover** [comment]
@barbalex I have a similar problem, but specifically Flow is creating dozens of instances of itself to max out RAM.

**Comment by caub** [comment]
Can confirm 

Columns are `Command     User    CPU%    RSS    VM-Size   PID `
![2018-02-03-100751_619x201_scrot](https://user-images.githubusercontent.com/3134574/35769285-09cd1950-0909-11e8-80eb-123451c079de.png)

**Comment by willisplummer** [comment]
This happens to me too - had to disable the vscode extension

**Comment by jinshin1013** [comment]
Has there been any active movement on trying to fix this problem?

**Comment by indolering** [comment]
What about excluding `./**/node_modules/` and JSON or JS files over a certain size by default?

**Comment by Mayank1791989** [comment]
I am closing this issue as flow has improved a lot (try using new version of flow). Also, this plugin switched to using lsp which will fix plugin spawning lot of processes.
