### ISSUE TITLE
Can't handle big projects with multiple working directories

### ISSUE THREAD

**Issue by rogerkerse** [flowtype/flow-for-vscode#165]
Is there an option to get it working with big repos where under one workspace you have multiple projects.
Exactly like `vscode-eslint` does it with their `"eslint.workingDirectories"` property.

**Comment by orta** [comment]
Nope, there's no option like that today. You're welcome to take a look at it, but you might be better off getting #150 shipped so that it can be handled inside by flow language server.

**Comment by Mayank1791989** [comment]
try v1.1.0
