### ISSUE TITLE
Wrongly telling us missing annotation - when retun is typedef'ed

### ISSUE THREAD

**Issue by Noitidart** [flowtype/flow-for-vscode#169]
I am using flow 0.53.1 and it keeps telling me missing annotation in this instance:

    type UpAsyncAction = { type:typeof UP_ASYNC, times:number };
    const upAsync = (times=1): UpAsyncAction => ({ type:UP_ASYNC, times });

The `times` argument gets underlined saying as in this screenshot:

![](https://i.imgur.com/34RmBfb.jpg)

> parameter `times` (Missing annotation)

Doing a try in the REPL: https://flow.org/try/#0MYewdgzgLgBAqgBQPoEEDKBNAcgYRgXhgEYBuAKDKgE8AHAU3hpQirGBWCgEtwCYBvGNXoAuYXRAAzeMnTYcAGiFcAtnQgiwAVxUAjOgCcYAX3KhIsLUxZs+ACm5qIAShGNmrdpx5gCAPhg7QXERRFRMXCVHdRNnciA

Shows no errors.

**Comment by Mayank1791989** [comment]
Try with new version of plugin and flow. Can't reproduce on my system.
