### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Brakkar** [flowtype/flow-for-vscode#17]
Hello I installed the june update, but nothing happens and there is no 'flow' language selection in language selection menu from lower right corner.

how is this extension supposed to work ?

**Comment by nmote** [comment]
It now works with the normal JavaScript syntax. You no longer have to select Flow. I'm assuming that you have a `.flowconfig` file and have Flow installed, and that it works fine from the command line.

I did some brief testing before release but the truth is that I'm not sure whether #14 is fully resolved by this update. Not all Flow errors may appear with recent versions of Flow. Unfortunately I don't have very much time to dedicate to maintaining this package.

**Comment by nickcox** [comment]
I have a .flowconfig, Flow installed and works from command line:
```
src/_spikes/_spikes.js:7
  7: console.log(getString(1, 2))
                 ^^^^^^^^^^^^^^^ function call
  7: console.log(getString(1, 2))
                           ^ number. This type is incompatible with
  3: function getString (x: string, y: string): string {
                            ^^^^^^ string

src/_spikes/_spikes.js:7
  7: console.log(getString(1, 2))
                 ^^^^^^^^^^^^^^^ function call
  7: console.log(getString(1, 2))
                              ^ number. This type is incompatible with
  3: function getString (x: string, y: string): string {
                                       ^^^^^^ string
```

But I don't see anything at all in VS Code. What should I check?

**Comment by IhorSyerkov** [comment]
+

**Comment by MGGMPE** [comment]
Same here. I don't see any syntax validation in the editor. Flow works good from terminal.

**Comment by zv3** [comment]
Had the same issue with .jsx files, renamed it to plain .js and the intellisense began working.

**Comment by orta** [comment]
More modern versions of VS Code default `*.jsx` files to use `javascriptreact` which means this extension will now work with them. 

If you're not seeing the the editor support, double check the instructions in the README 👍
