### ISSUE TITLE
Intellisense locks-up with latest VSCode version and flow extension enabled

### ISSUE THREAD

**Issue by bodiddlie** [flowtype/flow-for-vscode#170]
Running the latest release of VSCode (1.17.0), and the latest version of the extension (0.7.2). After a few minutes in the editor, code completion and intellisense stop working. Try to manually invoke intellisense just shows a loading message as below. Disabling just this extension seems to resolve the issue.

![intellisense](https://user-images.githubusercontent.com/2413413/31350031-6fa74c68-acda-11e7-99c1-0284981185ea.png)

**Comment by fwilkerson** [comment]
I also had this issue. I re-installed vscode 1.16.1 and the issue was resolved.

**Comment by bodiddlie** [comment]
I think this is actually not related to this extension and appears to be a bug in VSCode itself. Here's the relevant issue: https://github.com/Microsoft/vscode/issues/35847
