### ISSUE TITLE
Intellisense suggests wrong property name for flow spread type

### ISSUE THREAD

**Issue by danieljvdm** [flowtype/flow-for-vscode#171]
Give the following type:

```
type Props = {
  listings: ListingModel[],
  ...ScreenProps,
  ...NavigationProps,
};
```

```
export type ScreenProps = {|
  screenProps: {
    tabBarVisible: boolean,
    currentRoute: RouteName,
  },
|};
```

I get this intellisense (note that the property name is suggested as uppercase):

![image](https://user-images.githubusercontent.com/3450486/31472894-5aa16402-aebf-11e7-85ca-a98f46655cbc.png)

However, if I ignore it and type it in `this.props.screenProps` (lowercase) it doesn't complain and actually gives me the correct suggestions from that field:

![image](https://user-images.githubusercontent.com/3450486/31472929-8b58e912-aebf-11e7-8e4b-0acb07968fc0.png)

**Comment by Mayank1791989** [comment]
NavigationProps and ScreenProps suggestions are coming from typescript plugin. Try disabling the typescript plugin it will work.
