### ISSUE TITLE
Go to definition opens typescript definition

### ISSUE THREAD

**Issue by belemaire** [flowtype/flow-for-vscode#175]
Don't think this is an issue with `flow-for-vscode` itself, but when I click on `Go to definition` it is opening the associated `.ts` (typescript) type definition file instead of flow. The rest of the integration with vscode is properly working, just wondering how to make the go to definition properly work.

I can see the feature is listed in the README (`Go to Definition / Peek Definition`) but no specific instructions on this one, so I thought it would be supported out of the box without extra configuration, so not sure about this.

Thanks.

**Comment by renato** [comment]
@belemaire i'm new to vscode (and flow), how did you solve this?
