### ISSUE TITLE
Path completion for import not working...

### ISSUE THREAD

**Issue by Panoplos** [flowtype/flow-for-vscode#176]
Please see this issue report for details: https://github.com/Microsoft/vscode/issues/36488

**Comment by Mayank1791989** [comment]
The path completion is provided by typescript plugin there is nothing we can do here to fix it. May be you can use some other plugin for path completion. I use this https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete it works fine with flow.
