### ISSUE TITLE
VSCode error: [js] 'type aliases' can only be used in a .ts file.

### ISSUE THREAD

**Issue by johnunclesam** [flowtype/flow-for-vscode#177]
How can I use this plugin today?

If I set `"javascript.validate.enable": false` I loose something important.

There is no way to really fix this today?

![image](https://user-images.githubusercontent.com/21275217/32146348-5c8d9130-bcd6-11e7-93a3-f8bef5421979.png)

**Comment by orta** [comment]
Nope, I'm afraid the setup instructions are still up to date.
