### ISSUE TITLE
Show "Warning" level errors.

### ISSUE THREAD

**Issue by ajhyndman** [flowtype/flow-for-vscode#180]
Flow recently added support for optional lint rules with a configurable warning level.

It looks like the `flow-for-vscode`does not currently consume warning level feedback from the flow server to display.

This would be a great feature going forward.

**Comment by orta** [comment]
Likely would come for mostly free with #150

**Comment by matchu** [comment]
Did this end up happening? I just upgraded to latest Flow, and I'm noticing that messages for unused `$FlowFixMe` comments no longer appear in my VS Code output, presumably because it's now a warning-level message?

**Comment by matchu** [comment]
I've activated the `include_warnings` setting in my `.flowconfig` file, and warnings now appear for me in VS Code as warnings. But the Flow docs seem to suggest that IDE integrations will generally show warnings without this flag needing to be enabled?

**Comment by Mayank1791989** [comment]
fixed in https://github.com/flowtype/flow-for-vscode/pull/295.
