### ISSUE TITLE
Syntax Highlight Broken

### ISSUE THREAD

**Issue by dijonkitchen** [flowtype/flow-for-vscode#183]
Bringing this over from https://github.com/Microsoft/vscode/issues/38071

I found no instance of this issue in a Github search. 

- VSCode Version: 1.18.0
- OS Version: 10.13 (High Sierra)

Steps to Reproduce:

1. Create a `.js` file that has React code
2. In the render method, using a for loop and an if statement nested within it, chain some methods like `push`. 
3. Incorrect syntax highlighting

```js
// @flow
for (let i = postLen; i >= 0; i--) {
  if (node) {
    const element = ((node: any))
  }
}

for (let i = 0; i < postsLen; i++) {
  if (
    prevPost &&
    prevPost.creatorId === post.creatorId &&
    post.timestamp < prevPost.timestamp + 300
  ) {
    postsWithBreaks.push(renderPost(post, true))
  } else {
    postsWithBreaks.push(renderPost(post, false))
  }
}
```

Reproduces without extensions: Didn't test

I suspect it something to do with nesting of parentheses and multiple boolean operators in the if statement. When I add parentheses on the if statement to be more explicit, highlighting is corrected. 

This problem existed yesterday too before I upgraded to 1.18.0.

**Comment by orta** [comment]
This extension don't ship a syntax for flow, I'm afraid it's likely another extension.

**Comment by orta** [comment]
Maybe see if https://github.com/flowtype/flow-for-vscode/issues/34#issuecomment-343400849 works for you?

**Comment by dijonkitchen** [comment]
Thanks. I resolved this by not doing `((node: any))` and instead annotating earlier when `node` is declared.
