### ISSUE TITLE
Flow coverage should be done ONLY for files linted with flow

### ISSUE THREAD

**Issue by lwchkg** [flowtype/flow-for-vscode#184]
It's bizarre that Flow coverage is enabled for a markdown file, e.g. README.md. It doesn't make sense.

![image](https://user-images.githubusercontent.com/4113719/32700994-f83523ba-c7c5-11e7-83bc-c79ee7a72586.png)

**Comment by orta** [comment]
Yeah agreed, PRs are welcome 👍
