### ISSUE TITLE
ext does not work if I use vsc workspace

### ISSUE THREAD

**Issue by jeasonstudio** [flowtype/flow-for-vscode#189]

**Comment by orta** [comment]
It doesn't yet, no you're welcome to take a look at adding support though 👍

**Comment by jeasonstudio** [comment]
![image](https://user-images.githubusercontent.com/17971291/33467625-cc44bdd6-d690-11e7-96ea-d7258b640401.png)

@orta it's important to add the support of vsc workspace

**Comment by orta** [comment]
Awesome, then you're welcome to put some time in 💯
