### ISSUE TITLE
Is there any way at all to correctly highlight Flow in VSCode?

### ISSUE THREAD

**Issue by denizdogan** [flowtype/flow-for-vscode#193]
First of all, thanks for providing this extension, it's really helped me a lot in my daily work.

There are problems with regards to syntax highlighting, as you are aware of. I know that this extension does *not* provide syntax highlighting, but it's not clear to me which extension, if any, that correctly highlights the simple snippet below. This is surprising to me, since VSCode (and Flow) has so many users today.

I've tried the following extensions (one at a time, making sure to avoid conflicts):

- Sublime Babel
- Latest TypeScript and JavaScript Grammar
- JavaScript Atom Grammar

I have a file open with the following content:

```js
/* @flow */
for (const foo: Foo of foos) {}
```

The result is:

<img width="265" alt="screen shot 2017-12-12 at 11 23 08" src="https://user-images.githubusercontent.com/50928/33879496-de6d7c86-df2e-11e7-960f-91134f8cf1f6.png">

As you can see, I have not defined the `Foo` type at all, but Flow for VSCode doesn't indicate a problem with that. On top of that, the `of` keyword has been highlighted incorrectly. When I mouseover `of`, nothing pops up.

This is just a basic example, in my actual code (which I can't show) the highlighter completely breaks down on this piece of code and everything below it is incorrectly highlighted in various ways.

**Comment by orta** [comment]
At the core, https://github.com/flowtype/flow-for-vscode/issues/187#issuecomment-346872848 is the answer for this request

**Comment by kumarharsh** [comment]
@denizdogan Use babel javascript plugin (mgmcdermott.vscode-language-babel) for correct flow highlighting
