### ISSUE TITLE
Don't show 'Cannot find flow in PATH' error if there is no .flowconfig file in the project

### ISSUE THREAD

**Issue by ianwalter** [flowtype/flow-for-vscode#195]
Error:
```
[Flow] Cannot find flow in PATH. Try to install it by npm install flow-bin -g
```

I know most core users probably have flow installed on all of their devices, but if you are a casual user like me (I only use flow when I'm contributing to open source projects that use it) it's pretty annoying to see this error on a device in which I don't have or want flow installed. Since this error only seems to appear when I open a JavaScript file, I think a good compromise would be to only show this error if the project/workspace has a .flowconfig file.

**Comment by orta** [comment]
There's discussion about why this won't work in https://github.com/flowtype/flow-for-vscode/pull/95 alas, if you can think of a good answer, I'm happy to get that in.

**Comment by ianwalter** [comment]
@orta I would move the conditional you added to `checkFlow` so that `window.showErrorMessage` is only called if both conditions are true:
1. A .flowconfig is not found in root
2. Flow is not found

The users who have .flowconfig in a subdirectory are then not going to care about this change since this only affects whether the error message is displayed and they probably have flow installed globally anyway.

**Comment by jquense** [comment]
There at least needs to be the option to turn this error off. It's so unhelpful to see this everytime i open vsCode regardless of language or project

**Comment by orta** [comment]
Happy to take PRs on this 👍

**Comment by eyal0803** [comment]
Not really a solution but if you really jump between a lot of project in VS Code than you probably should set `flow.enabled` to `false` in the global settings and enable it (set to `true`) in each relevant project's workspace settings.
