### ISSUE TITLE
Does not uninstall

### ISSUE THREAD

**Issue by leanne1** [flowtype/flow-for-vscode#196]
On Mac OSX 10.3.2 VSCode 1.19.1. When I select Uninstall it says indefinitely Uninstalling but it does not uninstall even after several hours. When I close VSCode and reopen the plugin is still installed and the Uninstall option is present.

**Comment by orta** [comment]
I'm pretty sure this isn't something that this plugin can have an effect on. So I'm going to close this. I'd recommend looking at your vscode setup.
