### ISSUE TITLE
Very slow codeLoadingTime

### ISSUE THREAD

**Issue by klaytonfaria** [flowtype/flow-for-vscode#197]
The extension is too slow, increasing vscode CPU usage (48% in average). Some stats below:

- Extension Name: flow-for-vscode
- Extension Version: 0.7.3
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.20.0-insider

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 4432,
		"activateCallTime": 49,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascript"
	}
}
```

**Comment by caub** [comment]
see #164

**Comment by orta** [comment]
Yeah, calling this a dupe of #164
