### ISSUE TITLE
Jsx Format

### ISSUE THREAD

**Issue by maxval94** [flowtype/flow-for-vscode#20]
How to configure files.associations for babel extensions?
http://joxi.ru/1A5xOWKuKNKkg2

**Comment by code4aman** [comment]
Maybe overriding default `jsx` language would help. I got it working with `vscode-flow` extension.
```json
"files.associations": {
  ".jsx": "javascript"
}
```
Default language is `javascriptreact`.

**Comment by orta** [comment]
Flow doesn't ship with any language grammars, if that's your problem - then I'd recommend upgrading to [microsoft's latest grammars](https://github.com/Microsoft/TypeScript-TmLanguage)
