### ISSUE TITLE
React.Fragment is not found

### ISSUE THREAD

**Issue by Tanoemon** [flowtype/flow-for-vscode#203]
Error occurs like the below.<br>
![flow1](https://user-images.githubusercontent.com/11087495/35324754-085ee03e-0135-11e8-9d1d-f0290b37d389.png)

But code completion works fine.<br>
![flow2](https://user-images.githubusercontent.com/11087495/35324853-5c7e1d60-0135-11e8-8100-073e0ab927c7.png)
**Versions**
flow-for-vscode 0.7.3
React 4.2.0

**Comment by Mayank1791989** [comment]
Use some latest version of flow.
