### ISSUE TITLE
Uncaught errors

### ISSUE THREAD

**Issue by wmertens** [flowtype/flow-for-vscode#205]
- Extension Name: flow-for-vscode
- Extension Version: 0.7.3
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.19.3

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 1813,
		"activateCallTime": 25,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascriptreact"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

I noticed these uncaught errors in my extensions overview. Perhaps this is from somewhere in https://github.com/flowtype/flow-for-vscode/blob/f55c0afc3f25daea2c327352d5d7409643d95beb/lib/flowDiagnostics.js ?

**Comment by orta** [comment]
Agree, that's a shame, might be worth making a PR adding support?

**Comment by Mayank1791989** [comment]
Already fixed.
