### ISSUE TITLE
Add support for other extensions besides ".js"

### ISSUE THREAD

**Issue by xrei** [flowtype/flow-for-vscode#206]
- Extension Name: flow-for-vscode
- Extension Version: 0.7.3
- OS Version: Win10x64
- VSCode version: 1.20

# Problem
Any way to disable this error not only in .js files? for example  this is .vue file

![image](https://user-images.githubusercontent.com/9521710/35977948-686e144c-0cf5-11e8-93ff-b5864981aafd.png)

`"javascript.validate.enable": false,` is present in settings

**Comment by orta** [comment]
Unsure, you might want to look into the code for vscode around this.

**Comment by xrei** [comment]
Well, figured it out.
For someone writing flow with vue just write
`<script lang="js">....` that's all.
