### ISSUE TITLE
Unable to use this plugin with locally installed flow

### ISSUE THREAD

**Issue by vampolo** [flowtype/flow-for-vscode#209]
Hi.

I've flow installed in my `node_modules` folder and i setup `"flow.useNPMPackagedFlow": true,` in the configuration as suggested in the readme to use locally installed flow but i still get the error that `[Flow] Cannot find flow in PATH. Try to install it by npm install flow-bin -g`

Is it possible to do not install flow globally and still use this plugin?

**Comment by FezVrasta** [comment]
I have the same problem, actually the project structure is as follows:

```
- folder1/
  - folder2/
    - node_modules
    - index.js
```

So I think the problem is that this plugin looks only for `node_modules` on the top of the workspace folder and not on subfolders.

Maybe you may add a workspace specific setting to define the position of the `flow` binary?

**Comment by peterschussheim** [comment]
@orta @gabelevi (sorry for mention, however, this issue is still a problem).

I'd be happy to make a PR for this fix, provided I understand why the existing support for local `flow` binary fails.

**Comment by ptboyer** [comment]
Yep, `"flow.useNPMPackagedFlow": true` does work as expected only if `node_modules` is available at the root of the project workspace.

And `"flow.pathToFlow"` does work as expected with an absolute path, but that means that workspace is unique to my machine, which is alright for now.

However, `"flow.useNPMPackagedFlow"` doesn't work when the `node_modules` folder is nested in a workspace subfolder. I think the best approach would be to be allow `"flow.pathToFlow"` to specify a **relative** folder to source `flow` from, as @FezVrasta suggested, something like: `"./frontend/node_modules/.bin/flow"` or `"${project}/frontend/node_modules/.bin/flow"`

Definitely would love to see this resolved, currently working in a workspace structure like this, and would love to not need to only inspect one folder as a workspace at a time to get `flow` support! Cheers!

```
- myproject/
  - frontend/
    - node_modules/
      - .bin/flow (would be great to point to this one)
    - index.js
  - backend/
    - node_modules/
    - index.js
```

**Comment by orta** [comment]
That sounds like a pretty reasonable way to do it, yep
