### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by viskin** [flowtype/flow-for-vscode#21]
Flow [now supported on Windows](https://flowtype.org/blog/2016/08/01/Windows-Support.html).
But flow-for-vscode seems not working. **vscode presents no errors** in incorrect code.
I have .flowconfig and //@flow comments.
*flow check* command works and finds errors.

**Comment by f4k3N4m3** [comment]
I thought it because windows cmd does not recognize "flow" as command out of the \node_modules\.bin folder. I added path to PATH and now windows does the command any way. 
but the plugin still doesn't work on windows.

**Comment by motiz88** [comment]
I would like to take a stab at fixing this. Hope to send a PR soon.

**Comment by motiz88** [comment]
Actually, scratch that. I won't get around to it in the coming weeks. Sorry!

**Comment by rmevans9** [comment]
I have not found the fix yet but it is related to the fact that spawn errors out on windows if everything is not JUST perfect. So if someone were to spend some time coaxing the node and flow checks to work and anywhere else that uses spawn this might just work.

**Comment by rmevans9** [comment]
To add to that flow seems to also use spawn. This is causing crashes on my windows 10 machine. I dug up how React Native handles spawn for windows and started working through the places in this repo but it likely is becoming more complicated since it seems flow itself is actually crashing as well.

**Comment by kumarharsh** [comment]
@rmevans9 can you try replacing spawn with [cross-spawn](https://www.npmjs.com/package/cross-spawn)?

**Comment by rmevans9** [comment]
Yeah, I will give that a shot tonight. I believe that the problem with Flow will still exist but this might overcome the issues in this extension then a PR to flow might be able to resolve it over there.

**Comment by rmevans9** [comment]
I got it working! @kumarharsh cross-spawn did the trick. After playing with it for a few minutes I realized my earlier comment about flow also breaking was incorrect as the break was occurring in a different file within this repository. The following changes were made to make things seemingly work (more testing needed):

/lib/utils/util.js -> replace "import {spawn} from 'child_process';" with "import spawn from 'cross-spawn'"
/lib/pkg/commons-node/process.js -> import cross spawn then replace all occurances of "child_process.spawn" with just "spawn"

I am not sure if the files in pkg are shared throughout different Facebook repositories so I am not sure of the safety of changing it in this repository but those changes alone got Flow telling me about the errors I had setup to test the extension.

**Comment by kumarharsh** [comment]
wow, that's a really encouraging sign. can you prepare a PR, and I might also give it a run on my machine.

**Comment by rmevans9** [comment]
I will be in the next few days. I want to make sure my changes are solid before PRing it up.

**Comment by quincycs** [comment]
may i just add, that i'm really excited for this.  Also idk if you all are aware, but the lastest windows update brings the linux subsystem.   Would using that be helpful ,  maybe your already using it?

**Comment by kumarharsh** [comment]
I've tried using flow on linux subsystem, but sadly the flow server keeps crashing after parsing my code. Also, currently there is no way for the programs running within the ubuntu bash to communicate with windows apps.

**Comment by rmevans9** [comment]
PR Created.

**Comment by rmevans9** [comment]
@quincycs this is not using the linux subsystem. Just uses the fact that Flow now officially supports windows.

**Comment by quincycs** [comment]
Your the best!
