### ISSUE TITLE
Update the docs for when you can disable the TS extension in VS Code

### ISSUE THREAD

**Issue by orta** [flowtype/flow-for-vscode#211]
https://twitter.com/sandy081/status/965891223813869569

Someone could try this in advance and let us know what to change too.

**Comment by ValeryVS** [comment]
If I disable "TypeScript and JavaScript Language Features", then "go to definition" and "peek definition" show flow typings.

**Comment by orta** [comment]
Are there other downsides?

**Comment by orta** [comment]
Just ran this myself today for some work on Jest, looks like it seems to work solidly for me.

![2018-03-01 20_11_02](https://user-images.githubusercontent.com/49038/36878378-b627697a-1d8c-11e8-9f30-2f80ae915dbb.gif)

**Comment by orta** [comment]
I used this all weekend, it's definitely the right way to do it 👍

**Comment by orta** [comment]
Fixed by #216 now that this feature is in vscode prod.

**Comment by AVykhrystyuk** [comment]
> Are there other downsides?

I've just disabled Typescript Language Features but looks like VSCode used TS features for things like "Rename Symbol" (renames also all usages in project scope) so now I cannot use that renaming feature. Now only have option to "Change All Occurrences" which is not the same as it renames locally in file scope:
![image](https://user-images.githubusercontent.com/5488533/49609982-3db99b80-f9ae-11e8-8642-2a44f5f3972f.png)

@orta have you faced the similar issue?

**Comment by fabriziocucci** [comment]
> Are there other downsides?

Another downside of disabling `TypeScript and JavaScript Language Features` (besides the ones mentioned [here](https://github.com/flowtype/flow-for-vscode/issues/235#issuecomment-384043625)) is the loss of the shortcut for organizing imports (i.e. `SHIFT + ALT + O`).
