### ISSUE TITLE
Does this plugin really supply intellisense?

### ISSUE THREAD

**Issue by ryanzec** [flowtype/flow-for-vscode#212]
So I have a type defined at the top here what is show for the installed of a paramter defined as that type:

![screen shot 2018-02-27 at 7 52 25 pm](https://user-images.githubusercontent.com/444206/36765729-9eb99494-1c00-11e8-9b61-0fe5a59d5f0a.png)

This is pretty much the intellisense I would get with the flow plugin. Is this a bug as the intellisense in Atom is much more what I would expect?

![screen shot 2018-02-27 at 9 25 40 pm](https://user-images.githubusercontent.com/444206/36766652-cb75eac4-1c04-11e8-94e4-09b41b81cf2d.png)

**Comment by orta** [comment]
It should yep, if you want to look at improving it - I'd recommend taking a stab at wrapping up #150 so it can be inline with the atom version

**Comment by ryanzec** [comment]
Actually, my main problem seems to have been the fact that `javascript.nameSuggestions` is automatically set to true. Setting that to false cleans up my autocomplete in general and I get the same and atom.

While I would like to be able to make this plugin better, finding enough spare time to do that just in not there for me right now (plus since I don't know flow, the flow server, vscode development, etc. at all, it would take some ramp up time).
