### ISSUE TITLE
Flow Extension does not load

### ISSUE THREAD

**Issue by valpinkman** [flowtype/flow-for-vscode#214]
- Extension Name: flow-for-vscode
- Extension Version: 0.7.3
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.21.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 567,
		"activateCallTime": 18,
		"activateResolvedTime": 0,
		"activationEvent": "onLanguage:javascript"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by orta** [comment]
This isn't really enough to go on, I'd recommend cloning this repo and running it in debug.
