### ISSUE TITLE
flow not able to detect if folder includes index.android.js and index.ios.js

### ISSUE THREAD

**Issue by Noitidart** [flowtype/flow-for-vscode#219]
Is there a way we can indicate which file it should use? In certain folders i have `index.android.js` and `index.ios.js`. Is there a way to tell it which to take the type from? Currently it is not taking from either.

**Comment by orta** [comment]
I feel like this is a flow question, not for this extension

**Comment by Noitidart** [comment]
Roger that. Thanks very much for such a fast reply and your awesome extension!! Closing this out.
