### ISSUE TITLE
Flow not recognizing return type of imported method from node-modules with return type

### ISSUE THREAD

**Issue by svenlombaert** [flowtype/flow-for-vscode#220]
I was trying out your extension, and everything worked fine, until I had this setup:

I have two projects, where one is being used as a library by the other (it's installed over npm, so it's present in the node modules).

In my shared library I have this:
```javascript
// @flow
import { createSelector } from 'reselect';
import type { SelectorCreator } from 'reselect';
import type { State } from '../reducers';
import type { Tutorials } from '../reducers/tutorials';

export const selectTutorials = (state: State): Tutorials => state.tutorials;

export const getIsTutorialViewed = (tutorial: string): SelectorCreator => createSelector(
  [ selectTutorials ],
  (tutorials) => typeof tutorials[tutorial] !== 'undefined' && tutorials[tutorial],
);
```
In that library I installed the libdef for reselect, so I'd have the `SelectorCreator` as a return type. It recognises it correctly, because I can click through to the definition as well. When I import that function into my other project, then it goes wrong.

![](https://i.imgur.com/chHJjuc.png)

Return type is unknown, and I have no clue what I'm doing wrong.

KR

**Comment by orta** [comment]
Flow-IDE is a different project from this extension

**Comment by maranomynet** [comment]
https://github.com/jstwister/vscode-flow-ide

**Comment by Mayank1791989** [comment]
Looks like the issue is for some other plugin.
