### ISSUE TITLE
Generics on arrow functions breaks syntax highlighting for the rest of the file

### ISSUE THREAD

**Issue by MarkKahn** [flowtype/flow-for-vscode#225]
```js
function foo<T>(n:T): T { return n; }
function foo(){}
const foo = <T>(n: T): T => n;
function foo(){}
```

yields:
![image](https://user-images.githubusercontent.com/320562/38170281-dd197066-35b3-11e8-9446-10112e3f7375.png)

Notice that syntax highlighting is broken on the last line, and on every line that follows in the file

**Comment by orta** [comment]
Basically https://github.com/flowtype/flow-for-vscode/issues/187#issuecomment-346872848 is the answer to this request

**Comment by tom-wagner** [comment]
For those looking for a fix: https://github.com/flowtype/flow-for-vscode/issues/187#issuecomment-430133463
