### ISSUE TITLE
Flow not detecting .flowconfig within subfolders when `flow.useLSP` is true

### ISSUE THREAD

**Issue by kumarharsh** [flowtype/flow-for-vscode#228]
I have the flowconfig in a subdirectory `{ROOT}/src`. When I start VSCode, it shows `no valid .flowconfig was found...`. If I set `useLSP` to false, flow runs.

**Comment by OutThisLife** [comment]
Yep. This plus #172 really suck.

**Comment by romanlex** [comment]
Anybody known when subfolders will be support for LSP?

**Comment by kumarharsh** [comment]
ping...

I believe this is something which will have to be implemented within the flow binary itself, right?

**Comment by orta** [comment]
I don't think so, but I've not really researched it, the LSP [is here])(https://github.com/flowtype/flow-language-server)

**Comment by thymikee** [comment]
Just a quick glance, so not sure if it makes sense, but maybe we could pass `workspaceFolder` to `serverOptions` here:
https://github.com/flowtype/flow-for-vscode/blob/edec8445d810dfad0cc1fd5eab4ed76584e0cb99/lib/flowLSP.js#L49-L56

And that would do the trick? Maybe we could fix vscode workspace support this way. I'll try to find some time for this during the week, but if anybody feels adventurous, feel free to grab this!

**Comment by kumarharsh** [comment]
@orta - forgive me if I'm wrong, but the LSP you linked to is the deprecated one and the new LSP is implemented directly inside the flow binary...

**Comment by thymikee** [comment]
yup, we're going to use the new version, however we need to figure out from which version of Flow we should use which server (feature-parity LSP implementation in binary landed not so long ago)

**Comment by kumarharsh** [comment]
I see. I actually had a patch which fixed the nodejs based LSP to accept a different root folder, but didn't make a PR after learning that it had already been deprecated in favour of the flow-binary bundled LSP. Would it be useful if I make the PR for the old LSP?

**Comment by thymikee** [comment]
yep, hopefully @wbinnssmith could look at it :)
