### ISSUE TITLE
Hundreds of cmd.exe, node.exe, flow.exe processes.

### ISSUE THREAD

**Issue by OutThisLife** [flowtype/flow-for-vscode#231]
I ran vscode without any extensions, enabling one-by-one during dev sessions. As soon as I hit this ext. (last one to activate), I saw CPU spike to ~90% over about 5 minutes.

Seems like maybe using the integrated terminal w/ a node server may be causing issues. I don't know exactly, but it's obviously unacceptable.

**Comment by Sycoraxya** [comment]
I'm also having this problem, seems to be happening after VSCode's latest update

**Comment by HyperBrain** [comment]
Today my computer got slower and slower when having a flow-enabled project open in VSCode.
After inspecting Windows' TaskManager I saw that it spawned **more than 1,400 flow subprocesses**!!!!.

My computer was just before dying and only `taskkill /IM flow.exe /F` helped.

For me this is a blocker (never had such behavior with Atom before - even VSCode worked in an older version some time ago)

**Comment by OutThisLife** [comment]
I've since switched to Atom and have had zero problems, beyond Atom's usual slowness. :)

**Comment by orta** [comment]
Happy to take PRs on this, or to improve the flow LSP support so that this extension doesn't need to handle processes itself.

**Comment by HyperBrain** [comment]
FYI: I just checked with `useLSP` enabled - well, the load vanished, but the Flow checks too 😏 It seems that LSP somehow does not work for me at all.

**Comment by HyperBrain** [comment]
@OutThisLife 
UPDATE: The `useLSP` suddenly started working - I have no clue why. The behavior is a bit, well, strange. I have to click the problems in the problem list, and it will immediately recheck and remove the error from the problem list. But it works.
Additionally, this solves the OOM and flow.exe processes issue effectively.

IMO it would best approach to *not* invest more time on solving the process issue, but put the efforts onto finalizing and stabilizing the LSP implementation.

**Comment by thymikee** [comment]
@HyperBrain LSP is where we want to focus. Slowly, but working on making it better.

**Comment by OutThisLife** [comment]
@HyperBrain 
I can confirm, LSP is working. Thanks guys!
