### ISSUE TITLE
Duplicate errors from eslint-plugin-flowtype and flow

### ISSUE THREAD

**Issue by psamim** [flowtype/flow-for-vscode#233]
Hi,

I have `eslint-plugin-flowtype` in my project so I get the same error twice, one from eslint and one from flow. I do not want to set `"flowtype-errors/show-errors": "none",` in my eslintrc because others rely on eslint to get errors. Can I make flow errors silent in VS Code?

Thanks

**Comment by Mayank1791989** [comment]
Duplicate of #275
