### ISSUE TITLE
Parameter hints for function from imported file

### ISSUE THREAD

**Issue by aks1994** [flowtype/flow-for-vscode#242]
Parameter hints show for function in same file, but not if I'm using the method after importing to another file.

Any suggestions on how to fix this? Is this intended behavior or a bug?

**Comment by thymikee** [comment]
AFAIK function parameter hints come from builtin TypeScript extension, not from Flow.

**Comment by aks1994** [comment]
Thanks for replying. But given that I have to disable builtin typescript extension to use this extension, is there any other solution to get back the function parameter hints?

**Comment by orta** [comment]
Nope, that data isn’t kept in flow at all I’m afraid, I have an issue on their repo for it so closing this
