### ISSUE TITLE
Publish Update to VS Code Marketplace

### ISSUE THREAD

**Issue by ajhyndman** [flowtype/flow-for-vscode#25]
I might be misinterpreting what I'm looking at.  It seems that the latest version of this plugin published to the vs code marketplace is 0.0.3?  The most recent version in this repo seems to be 0.2.0.  Is there something holding up an update?

I was able to get this extension running in VS Code 1.4.0 today.  It seems like code-completion, hover tooltips and syntax verification are all working as a result of #19.

I wouldn't mind pitching in if there's something that still needs addressing.  Thanks for the work everyone else has put into maintaining this tool.

**Comment by Arilas** [comment]
We need to find who have permissions for publish new version of extension. Who published it before? @nmote @bpasero Do you know?

**Comment by bpasero** [comment]
@Arilas yes in my email history I see that @nmote published the extension. I do not have the password for that publisher.

**Comment by nmote** [comment]
I published originally and have sent credentials to @gabelevi who I believe is planning to publish it.

**Comment by ajhyndman** [comment]
After setting up credentials, it should be a one-liner (`vsce publish`).

The script will read your `vscode:prepublish` and `version` attributes from `package.json`.  :+1:

**Comment by ajhyndman** [comment]
Would it be alright if I publish a clone under another name while we're waiting?  I'm happy to unpublish immediately once the official version goes up.

**Comment by nmote** [comment]
As far as I'm concerned that would be fine.

**Comment by ajhyndman** [comment]
Cool.  I've published it here, until such time as this version goes up!

https://marketplace.visualstudio.com/items?itemName=ajhyndman.flow-for-vscode-temp

I'll keep an eye on this issue to be ready for un-publication.

**Comment by gabelevi** [comment]
Hi guys, sorry for the delay. I wanted to clean up the repo for Flow v0.32.0 before publishing, but I got distracted. Finally got off my butt and did it today. flow-for-vscode 0.3.0 should be up on the marketplace now: https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

**Comment by ajhyndman** [comment]
Awesome, thanks @gabelevi!

I'm having a few issues with the version on the marketplace, as detailed in #33.

It looks it might just be a build issue.  (if I recompile on master, everything works. I also noticed some spec files got into the build that was published?)  Shall I leave my version up until that's sorted?

**Comment by gabelevi** [comment]
I've published 0.3.2 - hopefully things should be working now

**Comment by ajhyndman** [comment]
Seems great!  I've unpublished my version of the extension from the marketplace.

**Comment by gabelevi** [comment]
@ajhyndman Thanks!

**Comment by IlyaSV** [comment]
I can't install the latest version of extension.
Extensions manager shows 0.3.2 as the latest version. But after installation it shows that 0.0.3 is installed and there is no updates available.
