### ISSUE TITLE
Cannot find node in path

### ISSUE THREAD

**Issue by dominictwlee** [flowtype/flow-for-vscode#261]
OS: Ubuntu 16.04
flow-bin: 0.65.0

Whenever I open up a file i get the error message 'Cannot find node in PATH. The simplest way to resolve it is install node globally'. I assume this has something to do with using nvm? What can I do to remedy this?

When I type ```which node``` i get:
/domtwlee/.nvm/versions/node/v10.4.0/bin/node

So it is installed, perhaps the extension can't detect it's path?

**Comment by Pitt-Pauly** [comment]
I have the same issue. It seems to be tied to some issue with VSCode and nvm-based node installs as a whole.  

You can fix it by running `nvm use` before starting VSCode via command line.
Make sure you have a default node set.
list node version installed: `$ nvm ls`
set default: `$ nvm alias default <your version number here>
use it: `$ nvm use default`
run code: `$ code`

or if you have everything set up already use a one liner: `$ nvm use default; code`

**Comment by Pitt-Pauly** [comment]
I made a Unity launcher .desktop file for VSCode to set the node version before launching VSCode. 
You can find the [gist here](https://gist.github.com/Pitt-Pauly/c5a3e116d686b590177236268ff5c15d)

Let me know if that works for you :)

**Comment by dominictwlee** [comment]
@Pitt-Pauly Thanks! Seems to have fixed the issue.

**Comment by hnrchrdl** [comment]
I did the following to resolve this issue:
- put `alias code=nvm use default; code` in _.zshrc_ file (should work with _.bashrc_, too)
- reinstalled vscode
Now when I start code, it picks up the default nvm version before launching code.

**Comment by ericbiewener** [comment]
I find that opening a file/folder/workspace via the `code` CLI command solves this issue as well
