### ISSUE TITLE
[question] language server protocol vs normal

### ISSUE THREAD

**Issue by darekzak** [flowtype/flow-for-vscode#263]
Hi, what mode would you recommend, useLSP set to true or false?
Which gives richer experience?
Find references/rename doesn't work in any of those, right?

**Comment by thymikee** [comment]
Can't answer this easily, depends on what you prefer. E.g. LSP supports richer error messages and code outline, but there's no coverage and status yet. 
Find/rename is not in either, but you can use TypeScript LSP for that currently.

**Comment by minedeljkovic** [comment]
AFAIK rename will be enabled in flow LSP according to
[https://github.com/facebook/flow/commit/671c9ee8245114987f89f80f344a3ce7cc7228f0](https://github.com/facebook/flow/commit/671c9ee8245114987f89f80f344a3ce7cc7228f0)
