### ISSUE TITLE
Inconsistent typing of imported modules.

### ISSUE THREAD

**Issue by danm** [flowtype/flow-for-vscode#264]
It is my understanding that when you import a module in your project, it imports the types that were defined. In my project this only works half of the time with Flow, interestingly though, typescript picks up the type.

`Icons.js`
```
import audio from '../../Icons/audio.svg';  // flow asserts this is a string
import otherSVGs...
export { audio, ... }
```
`comp.js`
```
import { audio } from './Icons';  // flow thinks this is an any type and throw a coverage error.
```

This doesn't happen everywhere, only in some files where I can't see a pattern.

flow v 0.77.0
Flow language Support 0.8.2
VSCode 1.25.1

**Comment by QuotableWater7** [comment]
I downloaded this extension about the time this issue was opened, and this is the first thing I noticed. +1

**Comment by danm** [comment]
I cleaned up the directory which had many other files in and it sorted out the problem. Its still a bug, but I can't reproduce now so closing. If others get this bug, start removing files till it works to trace the problem.
