### ISSUE TITLE
Stopped working with latest version of VSCode 1.26

### ISSUE THREAD

**Issue by lurui1029** [flowtype/flow-for-vscode#267]
I've been using this extension for a long time with VSCode on Mac. Everything works fine. (means I have already setup all the necessary stuffs)

But Today I upgraded my VSCode to 1.26. The extension stopped working.  No checking and can't go to definitions.
I always have these settings in my VSCode Preference (and built-in javascript and typescript extensions are disabled):
```
"flow.useNPMPackagedFlow": true,
"flow.pathToFlow": "${workspaceRoot}/node_modules/.bin/
"flow.showStatus": true,
```
Found some output:
`[2018-08-15T09:25:43.666Z] [INFO] flow - Path to Flow: /Users/user/Myproject/node_modules/.bin/flow`
`[2018-08-15T09:25:44.113Z] [INFO] flow - [unknown]: Flow server in /Users/user/Myproject`
And The flow icon in the status bar keeps running:

<img width="214" alt="2018-08-15 17 31 42" src="https://user-images.githubusercontent.com/9585681/44141905-1931e002-a0b1-11e8-8909-529d34a0445e.png">

Any idea about this?
Thanks.

**Comment by stylejy** [comment]
Same issue here.

**Comment by 0rvar** [comment]
Try running in LSP mode until it's fixed

**Comment by nikolay-borzov** [comment]
I don't even see Flow status icon.

**Comment by lurui1029** [comment]
Without any modification, the extension is working now.... Not sure what is going on, but it works now anyway. Closing this issue.

**Comment by nikolay-borzov** [comment]
Doesn't work for me on VS Code `1.26.1`
