### ISSUE TITLE
What does javascript.validate.enable": false mean?

### ISSUE THREAD

**Issue by bucaran** [flowtype/flow-for-vscode#27]
I am using flow in a JavaScript, not TypeScript, project. 

I was struggling to remove syntax errors where flow type annotations were used. 

Adding `"javascript.validate.enable": false` to my workspace fixes this issue. 

How is `"javascript.validate.enable": false` normally used? Is this likely to interfere with other projects? The README states to add this line, but does not reflect on any undesired side-effects I'd like to be aware of.

**Comment by rmevans9** [comment]
It is not a standard option. It basically turns off validations that VSCode tries to do. VSCode does not understand Flow types which is why you end up with syntax errors. The only real ramifications is that VSCode's built in code syntax checking doesn't run which shouldn't be a problem if you are using Flow.

**Comment by bucaran** [comment]
Makes sense! Thanks.

**Comment by djMax** [comment]
Although I get the theory, isn't this a pretty big tradeoff to make? VSCode does lots of syntax checking beyond types that flow doesn't catch right? Like eslint issues, for example... Is there some way to get flow to do all these things?

**Comment by reinhrst** [comment]
@djMax for future reference (seeing how your question has 40 upvotes): if you make all your flow files proper JS syntax (using [flow comment syntax](https://flow.org/blog/2015/02/20/Flow-Comments.html) ), you should be able to keep the normal VSCode JS tools.

Of course, whether this is practical depends on the project you work on.
