### ISSUE TITLE
Failed to write flow binary to disk

### ISSUE THREAD

**Issue by ArmorDarks** [flowtype/flow-for-vscode#273]
On Windows 10 enabling those two settings:

```
"flow.useLSP": true,
"flow.useNPMPackagedFlow": true,
```

results in following errors:

![image](https://user-images.githubusercontent.com/4460311/45572873-50bb4480-b873-11e8-9e31-d93c24158fbb.png)

```
Failed to write flow binary to disk.
Please ensure write access to C:\Users\serjl\AppData\Roaming\Flow\bin\0.80.0.
```

When `flow.useLSP` set to `false`, `flow-for-vscode` starts Flow normally and works as expected, and `npx flow-bin` works too.

I've installed `flow-bin` locally and globally — results are same.

I've also tried to launch VS Code as administrator — to no effect too.

**Comment by ArmorDarks** [comment]
I've checked where it actually tries to write and found following path:

```
C:\Users\serjl\AppData\Roaming\Flow\bin\0.81.0\Users\serjl\AppData\Roaming\Flow\bin\0.81.0
```

Note how it is recursively repeated. It seems that somewhere in the code typo causing the plugin to write bin into the wrong path...

**Comment by kumarharsh** [comment]
That's just one of the problems while settings `useLSP: true`. Even if flow does download, it won't start if your flowconfig is within a subfolder, and there is no way to configure it yet. See #228 and #272

**Comment by ArmorDarks** [comment]
I've actually even tried to put flow exe-file manually where it should be and add flowconfig to the root of the project, and with LSP enabled Flow just didn't start... like, nothing happened — no errors, nothing. Tooltips just always showed `loading`...
