### ISSUE TITLE
Hover on imported type shows only "Imported type from"

### ISSUE THREAD

**Issue by MikeYermolayev** [flowtype/flow-for-vscode#276]
Hi,

Is it expected behavior that on hover I only see 'Imported type from...' instead of real type presentation?

What's interesting that VS Code can easily show me real type definition if I switch import syntax to `import {type State}` but Flow still shows "imported type'

![image](https://user-images.githubusercontent.com/8783498/46078941-4fa4e400-c19e-11e8-94f4-9011172067c7.png)

**Comment by macrozone** [comment]
saw that too, makes usage of flow nearly useless in vscode :-/

**Comment by Tasemu** [comment]
Any news?

**Comment by yadomi** [comment]
Same here, very frustrating. 

Is this related to `flow-for-vscode` or `flow` itself ?

**Comment by XaxisJosh** [comment]
I believe this is related to https://github.com/facebook/flow/issues/7008 Flow changed the info that it returns about types. 

Does anyone know if there is a way to use the `--expand-json-output`  when flow-for-vscode calls flowService.flowGetType? this is a command line arg but I assume there is something similar for flowGetType -> type_at_pos

**Comment by vkosovskikh** [comment]
Dear contributors, please, fix this. Impossibru to write code without this import working.

**Comment by orta** [comment]
Hi @vkosovskikh - maybe you can take a look at fixing it?

FWIW, this is probably an issue at the Flow LSP level

**Comment by vkosovskikh** [comment]
@orta If I find some time, I can take a look. But I have no understanding on how to program vscode plugins. I know javascript only =)

**Comment by Mayank1791989** [comment]
closing see issue #310
