### ISSUE TITLE
Flow error is gone after saved (visual studio)

### ISSUE THREAD

**Issue by dopt** [flowtype/flow-for-vscode#278]
Hi, is that a normal when I am editing visual studio using flow, it shows error, but after I click save, the errors are gone?

**Comment by ArmorDarks** [comment]
Doesn't seem too. Wich OS do you use?

**Comment by thymikee** [comment]
This may happen if you're using `runOnEdit` (on by default) – Flow is then running in a local sandbox with this one file only, which makes is reasonably fast while editing, but doesn't have the whole app context, hence different error messages (or lack thereof).

**Comment by dopt** [comment]
> Doesn't seem to. Wich OS do you use?

Linux.

**Comment by dopt** [comment]
> This may happen if you're using `runOnEdit` (on by default) – Flow is then running in a local sandbox with this one file only, which makes is reasonably fast while editing, but doesn't have the whole app context, hence different error messages (or lack thereof).

But I was making some obvious error in a new file of new project just to test it out, apparently after saved, no error is detected for flow. Even if I `npm run flow` on the project, no error shows.

**Comment by ArmorDarks** [comment]
On Windows, I have a bug when Flow just stops to run after first save. It also can be seen in bottom toolbar that two instances of Flow appear. I thought you have the same issue, but considering you're on Linux, I doubt it.

**Comment by nonotest** [comment]
happens a lot to me (macos) have to restart vscode to get a normal state back

**Comment by gastonmorixe** [comment]
same here

**Comment by bradennapier** [comment]
Looks like this has happened recently.  Restarting doesnt fix it.  This makes a ton of sense I kept thinking something weird was going on!

**Comment by abdullahsari** [comment]
Extremely annoying and distracting, started happening to me as well on OSX.

**Comment by Mayank1791989** [comment]
Closing as not happening with latest flow and plugin version.
