### ISSUE TITLE
Flow for VSCode - $PropertyType with objects lint location and autocompletion

### ISSUE THREAD

**Issue by divyenduz** [flowtype/flow-for-vscode#280]
The following file, when used with `flow-for-vscode` only shows lint location for `v5` incorrectly and does not assist with autocompletion. 

```
/**
 * @flow
 */

type User = {
    name: string
}

type Custom = {
    s: string,
    n: number,
    o: User
}

const v0: number = "z"

const v1: $PropertyType<Custom, 's'> = "z" // should work
const v2: $PropertyType<Custom, 'n'> = 2 // should work

const v3: $PropertyType<Custom, 's'> = 2 // should fail
const v4: $PropertyType<Custom, 'n'> = "z" // should fail

const v5: $PropertyType<Custom, 'o'> = {
    nametypo: ""
}
```

For `v3`, `v4`, the error is shown at the value which is correct behavior IMO. 
For `v5` though, the error is listed at `$PropertyType` location, which is less helpful. In our [case](https://github.com/prisma/prisma-examples/tree/master/flow-graphql), the $PropertyType is in a separate file and we get the errors in a separate file. 

Here is demo based on this reproduction: http://recordit.co/lxS6C3GvU2

Here is an example of autocomplete not working with this setup: http://recordit.co/4AfVJ6afsx

**Environment**
VSCode: Version 1.27.2 (1.27.2)
Flow for VSCode: 0.8.4

P.S. Thanks for the amazing work on this plugin 🙌

**Comment by Mayank1791989** [comment]
Update to some latest version of flow errors are correctly positioned now and for autocomplete see issue #333.
