### ISSUE TITLE
What does this "Stop flow on exit" configuration do?

### ISSUE THREAD

**Issue by richardtks** [flowtype/flow-for-vscode#281]
Hi, 

I notice that in the configuration, there is a "Stop flow on exit". May I know what does this configuration do? 

Currently, when I exit the vscode, it does not kill the flow process that installed globally (Not inside the node_modules)? It is expected when the "Stop flow on exit" configuration being ticked?

![question](https://user-images.githubusercontent.com/43637878/46904929-b6582a80-cf1e-11e8-8ee3-b0450d7aabbe.png)

**Comment by stephen-last** [comment]
@richardtks @JoshRosenstein Are you both using a Windows OS..?

**Comment by richardtks** [comment]
> @richardtks @JoshRosenstein Are you both using a Windows OS..?

Nope, I am using Ubuntu 18.04.1 LTS.

**Comment by cprodescu** [comment]
On Mac OS I'm also noticing that flow processes seem to stay alive.
Is this not working or am I missing some other setting?

**Comment by Mayank1791989** [comment]
Try plugin v1.1.0 with useLSP: true, it's fixed now. Feel free to reopen issue.
