### ISSUE TITLE
Syntax coloring issue with flow polymorphic types

### ISSUE THREAD

**Issue by sandy081** [flowtype/flow-for-vscode#29]
_From @minedeljkovic on August 25, 2016 14:48_
- VSCode Version: 1.4.0
- OS Version:  Ubuntu 14.04 LTS

Steps to Reproduce:
1. Create .js file with [flow](https://flowtype.org/) type not using polymorphic types (coloring is ok)
2. Introduce polymorphic type (coloring is broken below the line where polymorphic type is used)

![vscode-flow-coloring](https://cloud.githubusercontent.com/assets/1811622/17973615/6d2b9082-6ae3-11e6-8e28-9a2d10c451eb.png)

_Copied from original issue: Microsoft/vscode#10958_

**Comment by gabelevi** [comment]
I suppose we probably need to add language colorization for Flow.

The [vscode docs on custom colorizers](https://code.visualstudio.com/docs/customization/colorizer) seem to say that all you need is a TextMate language specification file. Maybe we could for https://github.com/Benvie/JavaScriptNext.tmLanguage and go from there?

@thejameskyle - any insight? I'm wondering if there are some pre-existing flow grammars written for something that we could maybe reuse here

**Comment by Arilas** [comment]
@sandy081 What is the version of Flow extension? Extension from 0.2.0 don't have own color styling and uses standard javascript/typescript colors.

**Comment by minedeljkovic** [comment]
@Arilas this issues was moved by @sandy081 but created by me.

Flow extension that is used was built from [your pull request](https://github.com/flowtype/flow-for-vscode/pull/19) that made it work again.

**Comment by thejameskyle** [comment]
If you need tmLanguage stuff I would look in https://github.com/babel/babel-sublime as that's probably your best bet.

**Comment by levito** [comment]
Installing this standalone syntax extension solves the problem:
https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

**Comment by orta** [comment]
This is fixed in modern versions of VS Code, and if you're looking for support use the [new microsoft JS/TS grammers](https://github.com/Microsoft/TypeScript-TmLanguage)
