### ISSUE TITLE
does not work without `node` executable available

### ISSUE THREAD

**Issue by gabor** [flowtype/flow-for-vscode#290]
(on mac os)

it seems this extension requires a `node` executable being available. is this really necessary? i mean, visual-studio-code works without having a `node` installed, shouldn't this extension also work without having to install a `node` executable?

in my specific use case, i use `nvm` to manage node, and i do not have a `default` node. i activate node-versions when i work on the specific project. as a workaround i can do `nvm use lts/carbon` and then start visual-studio-code from that terminal-window and it will work, but i would prefer not having this restriction.

**Comment by orta** [comment]
I wouldn't imagine it as being necessary, so long as the extension can run flow somehow - you're welcome to take a look at fixing it 👍
