### ISSUE TITLE
please help, flow types didn't work

### ISSUE THREAD

**Issue by hsuehic** [flowtype/flow-for-vscode#293]
- Extension Name: flow-for-vscode
- Extension Version: 0.8.5
- OS Version: Darwin x64 18.2.0
- VSCode version: 1.29.1

 We have written the needed data into your clipboard. Please paste:
 
 flow types didn't work when codes were as follows:

```javascript
import type { SomeType } from './path/to/type';
```
but it worked when codes were as follows:
```javascript
import { type SomeType } from './path/to/type';
```

**Comment by noppa** [comment]
Did you get an error with the first example or did you just not get any type information? Does it work correctly when you run Flow from the command line?

**Comment by hsuehic** [comment]
Thanks a lot. Now it works. I have to start Flow Language Server manually .
