### ISSUE TITLE
{"flow.useNPMPackagedFlow": true} broke everything in vscode 1.30

### ISSUE THREAD

**Issue by DavidBabel** [flowtype/flow-for-vscode#298]
It seems that with the last 1.30 november update of vscode, the flow extension is broken if you set the `flow.useNPMPackagedFlow` option to `true`.
Worked in 1.29.1 without trouble

MacOs Sierra.

**Comment by colinrcummings** [comment]
As of vscode 1.30 I'm getting Output: `Could not find a .flowconfig in rootPath` in a project using subdirectories that was working prior to the update. My `"flow.useNPMPackagedFlow"` setting is set to `false`.

**Comment by ArmorDarks** [comment]
I wonder does 1.0 works for anyone at all? Windows 10, it does just nothing. Literally. Extensions do not start, no errors, no logs. Nothing.

**Comment by erkez** [comment]
Indeed, version 1.0 does not show types and does not flag errors while editing. I am using VSCode 1.30.1 in Linux.

**Comment by silvenon** [comment]
FWIW, for me it works fine with `flow.useNPMPackagedFlow`.

macOS Mojave 10.14.2
VS Code 1.30.1
Version of flow-for-vscode: 1.0.0

**Comment by ArmorDarks** [comment]
For me it partially works (https://github.com/flowtype/flow-for-vscode/issues/300) when `flow.useNPMPackagedFlow` _not_ used. With `flow.useNPMPackagedFlow` it even doesn't appear in `Output` panel. Windows 10

**Comment by Mayank1791989** [comment]
> With flow.useNPMPackagedFlow it even doesn't appear in Output panel. Windows 10

@ArmorDarks share your vscode `output (flow)` logs with following settings
```
flow.useNPMPackagedFlow: true,
flow.pathToFlow: "flow",
```

Make sure you open javascript file to start plugin (otherwise flow will not show up in output panel dropdown).

**Comment by Mayank1791989** [comment]
@colinrcummings check this [issue](https://github.com/flowtype/flow-for-vscode/issues/301)

**Comment by Mayank1791989** [comment]
Try v1.1.0.
