### ISSUE TITLE
Errors/Warnings provide a weird message

### ISSUE THREAD

**Issue by bpasero** [flowtype/flow-for-vscode#3]
This is due to the nature how FlowService.findDiagnostics returns errors. An error is typically composed of multiple errors with different positions in the file. VS Code however asks for a single error message with a position to present it. 

Ideally Flow could provide an option to return one error message as a fallback for those environments that ask for one error message to present to the user.

**Comment by Mayank1791989** [comment]
Vscode now supports multi errors so plugin works fine with it.
