### ISSUE TITLE
On Windows hangs after start

### ISSUE THREAD

**Issue by ArmorDarks** [flowtype/flow-for-vscode#300]
Hi

Unfortunately, Windows 10 experience still continues to be broken even with version 1.0 :(

Extensions launch successfully for the first time and show errors. However, after fixing errors and saving file a few times, it does not recompute errors. Status bar eternally shows spinner and `coverage` message:

![2018-12-20_22-48-03](https://user-images.githubusercontent.com/4460311/50309975-55624b00-04a9-11e9-8781-9456edb4febc.png)

Output show only message about launching

![2018-12-20_22-48-54](https://user-images.githubusercontent.com/4460311/50310028-79259100-04a9-11e9-99dd-9d0a12661387.png)

And in processes can be seen for some reason few Flow servers

![2018-12-20_22-49-36](https://user-images.githubusercontent.com/4460311/50310057-92c6d880-04a9-11e9-8224-b377546a4c68.png)

I just wonder, does it work for anyone on Windows at all? It seems to be broken for last few months completely.

My Flow extension settings are default, except this one:

```json
"flow.pathToFlow": "C:\\\\Users\\\\serjl\\\\AppData\\\\Roaming\\\\npm\\\\flow"
```

**Comment by Mayank1791989** [comment]
@ArmorDarks The issue is in [flow](https://github.com/facebook/flow) (windows). There is nothing we can do in this plugin to fix it.

@jbrown215 Do you know why this is happening on windows?

**Comment by ArmorDarks** [comment]
Can't reproduce with `1.0.1` and newer versions of Flow.
