### ISSUE TITLE
Doesn't work when .flowconfig isn't in project root

### ISSUE THREAD

**Issue by bsmith-cycorp** [flowtype/flow-for-vscode#301]
This extension was working without problems for about a week, and then suddenly it stopped working yesterday or the day before. My `.flowconfig` lives at `${projectRoot}/src/.flowconfig`, which is expressly supported by the Flow docs, but this extension now only works when I open `src/` as the project root.

I'm on OSX, with VSCode v1.30.1 and flow-for-vscode v1.0.0

**Comment by Mayank1791989** [comment]
In v1.0 useLSP is on by default which only supports .flowconfig in rooth path. Set useLSP to `false` for now.

**Comment by bsmith-cycorp** [comment]
Confirmed that that fixed the problem. Thanks.
