### ISSUE TITLE
Plugin doesn't work in a Monorepo environment

### ISSUE THREAD

**Issue by dnepro** [flowtype/flow-for-vscode#302]
Hello everybody,

First off thank you very much 👍

But i've got a problem working with it in a typical lerna project with packages where only some packages make use of flow and therefore i don't have a root-level ".flowconfig", is there some possibility to allow such an environment to work?

And for instance i make heavy use of `module.name_mapper` which i don't know if it would work from a root-level config.

If you need more info or some demo repository, let me know :)

Thanks in advance!

**Comment by noppa** [comment]
See #301  
Currently, you need to set `"flow.useLSP": false` in your settings if you don't have a root level flowconfig file.

**Comment by ManThursday** [comment]
@noppa Thanks for linking to that issue. I've just run into this as well and was stuck on some older issues that didn't have that context when I googled.

Do you happen to know what the impact of turning off that setting has on the extension? Does it change any of the functionality or is it purely an implementation detail?

From reading the issues it seems like support for non-root config files might not be on the cards until flow-for-vscode has switched over to using LSP support in Flow itself. Do you know if that's actually being worked on or if it's being tracked anywhere?

Apologies for deluging you with questions but it seemed like you might have a bit more context on this. Thank you regardless.

**Comment by Mayank1791989** [comment]
> From reading the issues it seems like support for non-root config files might not be on the cards until flow-for-vscode has switched over to using LSP support in Flow itself. Do you know if that's actually being worked on or if it's being tracked anywhere?

Hi, @ManThursday v1.0 already started using native `flow lsp` instead of `flow-language-server`. The support for multi-config and non-root config will be added soon.

> Do you happen to know what the impact of turning off that setting has on the extension? Does it change any of the functionality or is it purely an implementation detail?

Rename and server progress will not work. Also, lsp mode better handles flow processes. I would recommend lsp mode if your config is in root dir.

**Comment by Mayank1791989** [comment]
@dnepro Please share some demo repository.

**Comment by ManThursday** [comment]
@Mayank1791989 Thanks very much. We'd like to have different flow configs in each package so this will help us make a call on the best way to work around this for now.
