### ISSUE TITLE
"Flow Language Support" shows up in Breadcrumb navigation

### ISSUE THREAD

**Issue by pReya** [flowtype/flow-for-vscode#309]
Hey everyone,

VS Code offers [Breadcrumb navigation support](https://code.visualstudio.com/updates/v1_26#_breadcrumbs) since July. However when this is enabled, and I am editing Flow files, an additional (unnecessary) entity in the Breadcrums navigation will be added called "Flow Language Support". Any way to remove this?

<img width="809" alt="screenshot 2019-01-21 10 54 35" src="https://user-images.githubusercontent.com/4677417/51466886-82857000-1d6b-11e9-8707-710af7f0f92d.png">

**Comment by thymikee** [comment]
Same happens for TypeScript files and it's like this by design. Not sure if we can anyhow opt-out from it. Maybe we could change the display to just "Flow" or something, but it's probably taken from the extension name.

**Comment by pReya** [comment]
Thanks for the answer. Did not know that this affects other language modes as well. So I guess this would be something for VS Code to implement. Like making this additional entity optional or at least allowing to rename it and not making it the extensions name by default.
