### ISSUE TITLE
Shouldn't there be an error pane of some kind?

### ISSUE THREAD

**Issue by Meai1** [flowtype/flow-for-vscode#31]
Right now if my file has an error I need to have eagle eyes and look for the squiggly red lines. In all my files. The babel compiler doesnt seem to care at all if there is a flow error but having the errors appear in a separate cmd window isnt so good anyway.
Usually for example in Visual Studio, you would get errors in an output window and then you can click on them to navigate to the offending location.

**Comment by nmote** [comment]
VSCode provides no facilities to extend the UI (at least, last time I checked). All we can do is provide the errors to VSCode and then it's up to VSCode to display them. If there is no error pane in VSCode I don't believe we can add one.
