### ISSUE TITLE
LSP doesn't show information about imported types

### ISSUE THREAD

**Issue by ArmorDarks** [flowtype/flow-for-vscode#310]
LSP implementation lacks information about imported types aliases. As I remember, non-LSP-version was showing types.

![demo](https://user-images.githubusercontent.com/4460311/51787100-1ee9b100-2176-11e9-99df-0f737cdbb4d2.gif)

That makes imported types inspection problematic.

Imported types itself work as intended.

Flow `0.91.0`, `flow-for-vscode` `1.0.1`, default settings.

**Comment by Mayank1791989** [comment]
Thanks for reporting. I will look into it.

**Comment by ArmorDarks** [comment]
Might be related https://github.com/flowtype/flow-for-vscode/issues/276#issuecomment-461015965, though seems like the mentioned issue was related to non-LSP implementation

**Comment by Mayank1791989** [comment]
@ArmorDarks I looked into it but could not find a way to change the current behaviour. As we now started using `flow lsp` there is not much info returned by flow server to show type definition. But You can press `ctrl|cmd` to view declaration though.

**Comment by Mayank1791989** [comment]
fixed in https://github.com/facebook/flow/commit/44f313b1ecd

**Comment by Mayank1791989** [comment]
use flow `>=v0.102.0`
