### ISSUE TITLE
Show full error snippets in LSP errors

### ISSUE THREAD

**Issue by ArmorDarks** [flowtype/flow-for-vscode#311]
Given the type

```js
// @flow

export type Term = { prop: string }
```

compare LSP error with original Flow error:

![3](https://user-images.githubusercontent.com/4460311/51787264-3cb81580-2178-11e9-9c77-79680f099235.png)

![2](https://user-images.githubusercontent.com/4460311/51787262-37f36180-2178-11e9-93fe-aa7f548d914e.png)

Because LSP error doesn't show full code snippet in error, it is extremely hard to understand at glance what to referencing `1` and `2`

Flow `0.91.0`, `flow-for-vscode` `1.0.1`, default settings.

**Comment by thymikee** [comment]
This is what we get from Flow server. Maybe this code frame is hidden somewhere, but I don't recall that. It may be a better idea to move this issue to https://github.com/facebook/flow as `flow` binary is now responsible for feeding this data.

**Comment by ArmorDarks** [comment]
I wasn't sure is it what Flow server gives, or was it intentional, so posted here first. I'll escalate issue into Flow repository then, thanks.

**Comment by ArmorDarks** [comment]
Ref https://github.com/facebook/flow/issues/7394
