### ISSUE TITLE
Error: Autocomplete on unexpected type of value OpenT (please file a task!)") Code: -32001

### ISSUE THREAD

**Issue by josemigallas** [flowtype/flow-for-vscode#312]
I get this error when working with Enzyme in VSCode and the autocomplete feature doesn't work as expected.

For some reason it only works the first method:
![screen shot 2019-02-01 at 09 39 11](https://user-images.githubusercontent.com/11672286/52111970-7f10a500-2605-11e9-8975-1e27baf85028.png)

Then it doesn't show anything:
![screen shot 2019-02-01 at 09 39 32](https://user-images.githubusercontent.com/11672286/52111985-86d04980-2605-11e9-83dc-774bd736943a.png)

If I assign the first result to a variable then it works again:
![screen shot 2019-02-01 at 09 39 41](https://user-images.githubusercontent.com/11672286/52112011-964f9280-2605-11e9-8ba5-a522472f17c6.png)

And everytime the output console opens with this error:
```
[Error - 09:41:53] Request textDocument/completion failed.
  Message: (Failure
  "autocomplete on unexpected type of value OpenT (please file a task!)")
  Code: -32001 
[object Object]
```
Is this a problem with the typings maybe? I found out the following: in the typings definition some methods return `this`:
```
declare class Wrapper {
    find(selector: EnzymeSelector): this,
    findWhere(predicate: PredicateFunction<this>): this,
    filter(selector: EnzymeSelector): this,
```
However I changed it to return `Wrapper` and now the autocomplete works... is `this` not supported or something?

**Comment by Mayank1791989** [comment]
@josemigallas The error is coming directly from flow. Please file issue in flow repo. They will be able to give you a better answer.

**Comment by mroch** [comment]
agreed, please report upstream (though I am pretty sure this is fixed :) )
