### ISSUE TITLE
Syntax highlighting breaks after for loop

### ISSUE THREAD

**Issue by jasperkuperus** [flowtype/flow-for-vscode#314]
If you write a for typed loop, the syntax highlighting will break in/after the loop:

```
for (const order: Order of orders) {
  ... things break
}
... also breaks after the loop
```

![screen shot 2019-02-13 at 10 57 03](https://user-images.githubusercontent.com/1655683/52703255-34d0e180-2f7e-11e9-9a54-d83421453673.png)

The `try-catch` in the screenshot is not necessary to break the syntax highlighting, it just makes it  worse / clearer.

VSCode version: 1.31.1
flowtype.flow-for-vscode version: 1.0.1

**Comment by noppa** [comment]
I'd recommend using the [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) plugin for syntax highlighting. It fixes many problems like this.

**Comment by jasperkuperus** [comment]
@noppa Thanks! That works like a charm!

**Comment by Mayank1791989** [comment]
See https://github.com/flowtype/flow-for-vscode#known-issues.
