### ISSUE TITLE
Array.from intellisense is missing

### ISSUE THREAD

**Issue by Meai1** [flowtype/flow-for-vscode#32]
Hi, 
everything else seems to be working fine except for that. I tried nuclide in atom and there Array.from is working. 
I dont know what could cause this? I dont like atom, I want to keep using vscode if possible.

**Comment by gabelevi** [comment]
What exactly do you mean? Autocomplete isn't working, but only for `Array.from`? To help me out, can you specify

1. What are your steps to reproduce
2. What is your expected outcome
3. What is your actual outcome

Thanks!

**Comment by Meai1** [comment]
it appears to be fixed in the last update
