### ISSUE TITLE
Unknown --json-version option

### ISSUE THREAD

**Issue by eric-burel** [flowtype/flow-for-vscode#320]
Hi,

When I add `@flow` to a file, I get this error message in VS Code:

```Flow returned an error: flow: --json-version unknown option```

My Flow version is 0.57.3. 
Should I update, and do you think this bug could be related to this plugin ? I searched thoroughly on Google and here but did not find any reference to this `json-version` option, which indeed does not seem to exist.

**Comment by thymikee** [comment]
The latest Flow version is 0.94, so yea, you _should_ update :D

**Comment by Mayank1791989** [comment]
@eric-burel Are you sure error coming from this plugin as we are not using `--json-version` anywhere in plugin code. I tried switching to version 0.57.3 locally but can't reproduce. Which version of plugin are you using? Also note current version of plugin required atleast `flow >= 0.75`.

**Comment by eric-burel** [comment]
@Mayank1791989 Thanks for investigating this. Honestly it is hard to tell what produces this message, the log doesn't tell me which package is responsible, it could even be Code as well... I'll close for now until I can make more tests and update all the librairies/packages to be at the latest versions, I'll keep you informed.
