### ISSUE TITLE
Extension activates even for non-Flow (and non-JS) projects

### ISSUE THREAD

**Issue by erydo** [flowtype/flow-for-vscode#321]
The Flow extension, if installed, activates whenever VSCode is opened, regardless of whether a workspace or opened file even contains JavaScript. On my machine, this contributes a 100-200ms activation time, despite working in a workspace without JS.

(I know the extension can be selectively disabled, but that's kind of a pain! It shouldn't intrude where it's not relevant).

The commit b5be6578a7a51dfb4e38db4c2f1a1ad41c3afb82 included the following change to `package.json`:
```diff
   "activationEvents": [
-    "onLanguage:javascriptreact",
-    "onLanguage:javascript"
+    "*"
   ],
```

It's not clear from that commit why falling back to `"*"` was necessary in that change, and perhaps it was necessary. It looks like it might have been due to wanting to check for `.flowconfig` here https://github.com/flowtype/flow-for-vscode/blob/b5be6578a7a51dfb4e38db4c2f1a1ad41c3afb82/lib/flowLSP/handlers.js#L11-L15

I'm not super familiar with the extension APIs, but I believe this could be accomplished with the [`workspaceContains` activation event](https://code.visualstudio.com/api/references/activation-events#workspaceContains) instead, which would allow the extension to avoid loading in irrelevant contexts.

e.g.

```diff
   "activationEvents": [
     "onLanguage:javascriptreact",
-    "onLanguage:javascript"
+    "onLanguage:javascript",
+    "workspaceContains:**/.flowconfig"
   ],
```

**Comment by Mayank1791989** [comment]
@erydo Yes, you are right. That change somehow got committed with other changes. I will push the fix and thanks for pointing it out.
