### ISSUE TITLE
Restart vs Restart Client?

### ISSUE THREAD

**Issue by silvenon** [flowtype/flow-for-vscode#323]
Sometimes I get this dialog box and I don't know what "Restart" means.

<img width="464" alt="Screenshot 2019-03-27 at 12 44 02" src="https://user-images.githubusercontent.com/471278/55073491-27833880-508e-11e9-9898-800653d88416.png">

Maybe it should be more descriptive because "Restart" is semantically a superset of "Restart Client".

**Comment by orta** [comment]
Good question, probably worth diving into the codebase and figuring out what they did here 👍
