### ISSUE TITLE
Intelllisense can't pick up functions in plain objects properly

### ISSUE THREAD

**Issue by DanielHoffmann** [flowtype/flow-for-vscode#335]
See the following screenshots, intellisense manages to pick up normal properties, but functions sometimes it can and sometimes it can't based on what has already been typed:

![Screenshot 2019-06-05 at 16 47 10](https://user-images.githubusercontent.com/2980150/58966026-d7bd9d80-87b1-11e9-99ea-21c9440e7a13.png)

![Screenshot 2019-06-05 at 16 46 48](https://user-images.githubusercontent.com/2980150/58966035-dbe9bb00-87b1-11e9-8c29-56e1e0b072a0.png)

![Screenshot 2019-06-05 at 16 46 37](https://user-images.githubusercontent.com/2980150/58966037-dc825180-87b1-11e9-8754-53cadcd4c0cb.png)

![Screenshot 2019-06-05 at 16 46 26](https://user-images.githubusercontent.com/2980150/58966045-e015d880-87b1-11e9-9581-8172a9b73378.png)

Flow Language Support  v1.1.1
Flow version v0.100.0

Should I open this issue with Flow itself? Seems to be an extension issue.

**Comment by Mayank1791989** [comment]
Looks like bug in this plugin. Flow is returning all the fields.

**Comment by mroch** [comment]
the range Flow returns for snippets (used for functions but not other properties) is wrong, causing vscode to filter them out.

https://github.com/facebook/flow/pull/7816
