### ISSUE TITLE
Intellisense doesn't work over remote ssh with useLSP=true

### ISSUE THREAD

**Issue by jarkonik** [flowtype/flow-for-vscode#336]
Hover/autocomplete features don't work when using https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh in lsp mode.

**Comment by minedeljkovic** [comment]
Definition, references, document symbols, rename do not work, also.
Diagnostics, however, does work.

**Comment by Mayank1791989** [comment]
Enable `"flow.trace.server": "verbose"` and check for response of 'textDocument/hover' request.

**Comment by jarkonik** [comment]
There are no 'textDocument/hover' requests present in the log at all. 
I've also found out that everything works correctly using version 1.0.1 of the plugin(it is broken since 1.1.0).

**Comment by Mayank1791989** [comment]
@jarkonik Can you share some sample project which is not working. I tried mine its working fine with v1.1.0.

**Comment by jarkonik** [comment]
@Mayank1791989 Status bar displays flow version (0.93.0) (I've tried version 0.100 of flow too but it doesn't change anything) and coverage correctly. Even the "problems" tab is working ok - it displays all the flow type checking errors correctly.
```
// @flow
type MyType = {
    myField: string
};

function main() {
    const a: MyType = {
        myField: 'test'
    };
}
```
I've tried it with this code within a file named ```main.js``` in the project root directory and default ```.flowconfig``` file. Hovering over any of types/vars does not cause a popup to appear, IntelliSense shows only generic text-based autocompletion.

**Comment by Mayank1791989** [comment]
@jarkonik any progress?

**Comment by jarkonik** [comment]
@Mayank1791989 Are you sure you are not seeing builtin TypeScript extension autocomplete/hover data? I have tested it in multiple different environments and it never works.

**Comment by Mayank1791989** [comment]
@jarkonik I will test it again.

**Comment by Mayank1791989** [comment]
It's working fine.

**Comment by minedeljkovic** [comment]
@Mayank1791989 my team is using remote ssh extensively, and we are experiencing exact same symptoms as @jarkonik. It seems you are testing it differently

**Comment by ssenchenko** [comment]
the same issue with remote wsl

**Comment by ssenchenko** [comment]
also there are no type hints in remote wsl

**Comment by Mayank1791989** [comment]
@ssenchenko Is plugin starting correctly? (Look at `output > flow` panel logs or status bar widget to find.)
Also enable `"flow.trace.server": "verbose"` to see lsp logs and look for request and response. It looks like some setup issue.

**Comment by Mayank1791989** [comment]
@minedeljkovic Are you able to run the plugin? I tried again it's working for me. I am testing using linux machine for host and remote.

**Comment by minedeljkovic** [comment]
> I am testing using linux machine for host and remote

That seems to be the difference! I'm regularly using windows host and linux remote (and, extremely likely, so is @jarkonik), and I just tried it on linux host and linux remote, and it does work.
So my experience is that on windows host extension does not fully work after version 1.0.1 (as described [here](https://github.com/flowtype/flow-for-vscode/issues/336#issuecomment-499860992), [here](https://github.com/flowtype/flow-for-vscode/issues/336#issuecomment-500003593) and [here](https://github.com/flowtype/flow-for-vscode/issues/336#issuecomment-500339215)). On linux host, the latest version seems to work 100%.

**Comment by Mayank1791989** [comment]
@minedeljkovic Ok I will test with window host and try to find issue.

**Comment by Mayank1791989** [comment]
@minedeljkovic Ok I found the issue will push the fix soon.

**Comment by jarkonik** [comment]
@Mayank1791989 Seems that the issue reappeared again in vscode version 1.39.1

**Comment by romanlex** [comment]
I have same problem with flowtype and vscode remote WSL
