### ISSUE TITLE
1.1.2 breaks the useLSP: false mode

### ISSUE THREAD

**Issue by vojtatranta** [flowtype/flow-for-vscode#341]
- it will not start server at all
- it says that any command listed in the readme does not exist even though it is available in the commnad menu in VS code

**Comment by Mayank1791989** [comment]
Yes the useLSP: false mode is broken (due to this 43d24627c7a34abdcb03733b10a886263c62824b). I will push the fix for now you can use v1.1.1.

**Comment by balzdur** [comment]
FYI: still broken with v1.1.3

**Comment by vojtatranta** [comment]
Yeah I noticed that 1.1.1 works so its OK. I just reported it, bwmecause I noticed.

**Comment by Mayank1791989** [comment]
Will be fixed in v1.1.4
