### ISSUE TITLE
CHANGELOG.md and Releases tab are neglected

### ISSUE THREAD

**Issue by ksm** [flowtype/flow-for-vscode#345]
Hi y'all. 

First of all: thank you so much for maintaining and working on `flow-for-vscode` (👋 @orta ❤️ ).

I now use and benefit from this extension everyday at work. I'd like to contribute, but I'm still a little intimidated by Flow and VSCode's tooling/extension system.

Just a very humble request to please keep the CHANGELOG.md updated (🙏 @Mayank1791989 ). I noticed that there are new versions out, but none of the changes are specified in the CHANGELOG or the GitHub releases tab. 

Once again, thank you for all your work on this.

**Comment by orta** [comment]
Maybe you could add Danger to this repo to encourage CHANGELOG entries PRs?

**Comment by Mayank1791989** [comment]
Also we should setup a ci to do all releases which will publish the extension to marketplace and also update release tab.

**Comment by ksm** [comment]
Just updated the CHANGELOG btw. https://github.com/flowtype/flow-for-vscode/pull/346

@orta Danger looks like the perfect tool for this job. I'd be willing to give it a shot.

@Mayank1791989 Yeah, for sure, the release tab needs work. CI sounds like a fair bit of work though?
