### ISSUE TITLE
flow-for-vscode does not resolve flowconfig for documents outside project

### ISSUE THREAD

**Issue by vicapow** [flowtype/flow-for-vscode#348]
flow-for-vscode does not detect a project file when the project file lives up above the project root directory. for example:

./project2/.flowconfig (regular flowconfig file)
./project2/import-foo.js

````js
// @flow

import foo from '../foo.js';
// ...
````

foo.js
````js
export default function foo() {
  return 10;
}
````

Note that Flow does properly import and check this file so it does appear to be specific to flow-for-vscode.

I believe this is because flow-for-vscode resolves the .flowconfig relative to the current file path. In the case above, flow-for-vscode does not know foo.js is being run inside the project1 project. This appears to be the relevant code: https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowLSP/handlers.js#L37

**Comment by Mayank1791989** [comment]
Where is `.flowconfig` file?

**Comment by vicapow** [comment]
@Mayank1791989 apologies for not clarifying. It's at `./project2/.flowconfig` will update the example.

**Comment by Mayank1791989** [comment]
What error are you getting?. Is it `cannot resolve module 'some_path/foo.js'`.

**Comment by vicapow** [comment]
@Mayank1791989 in this case, there is no error or any output when you open foo.js in vscode. It seems  it's not registered as a "flow" related project because there is now .flowconfig it nows to be associated with the file. However, when you run flow from the command inline for the project, it does (correctly) give errors / output from that file.

**Comment by Mayank1791989** [comment]
What is the output of running `flow status` in `project2/` directory.

**Comment by vicapow** [comment]
`flow status project2` doesn't mean anything because there is no flow config at the root. but running flow status from within `project2` does produce the correct error as expected from the file at the root.

**Comment by Mayank1791989** [comment]
> but running flow status from within project2 does produce the correct error as expected from the file at the root.

Is running `flow status` inside `project2` directory giving you errors from `foo.js`? As for me `flow status` is giving this error `cannot resolve module 'some_path/foo.js'` which is same as what plugin is behaving.

![flow-348](https://user-images.githubusercontent.com/1512953/60232700-04e60300-98bb-11e9-8a0e-f7847dba7618.png)

**Comment by vicapow** [comment]
@Mayank1791989 Apologies again. You are correct. I tried to simply my example too much. The issue actually happens for modules that are symlinked. Instead of continuing here, I'll create a new ticket since this one is not valid.

**Comment by vicapow** [comment]
For reference the new ticket is here: https://github.com/flowtype/flow-for-vscode/issues/349
