### ISSUE TITLE
Cannot rename variable when cursor is at the end of variable

### ISSUE THREAD

**Issue by madacol** [flowtype/flow-for-vscode#350]
Issue Type: <b>Bug</b>

1. Wait like 30 seconds after VSCode is opened
1. Position cursor at the right's edge of variable
2. Press <kbd>F2</kbd> to rename variable
3. Change name
4. Press <kbd>Enter</kbd>
5. Variable is not modified

I disabled all extension except Flow and reloaded editor to pinpoint the extension causing it

Extension version: 1.1.4
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:55:08.091Z)
OS version: Linux x64 4.15.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.53GB (0.30GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|57%|
</details>

**Comment by Mayank1791989** [comment]
Try renaming `test` var on the code below
```js
function renameTest() {
	const test = "some_value";
	console.log(test);
}
```
Also share some simple case where it's not working for you.

**Comment by madacol** [comment]
> Try renaming `test` var on the code below

It works fine in a fresh workspace

---

### I just tested in a different environment with a fresh install of flow

### Setup the workspace:

1. Open a new empty folder with vscode
2. Add an empty `.flowconfig` file
3. Add another file with your sample content

> ```js
> // @flow
> function renameTest() {
> 	const test = "some_value";
> 	console.log(test);
> }
> ```

4. Set language to `Javascript`
5. Wait till flow completes coverage check 
![image](https://user-images.githubusercontent.com/6379896/61507852-0c299980-a9ad-11e9-9118-45eeeba08c1b.png)
6. Done!. 

Now If you put the cursor at the end of a variable then press <kbd>F2</kbd> and then try to rename it, it won't work.

**Comment by Mayank1791989** [comment]
Did you save the file before renaming?

**Comment by Mayank1791989** [comment]
@madacol Yes I can reproduce the issue now. It's happening when cursor is in the end. I will look into it. Thanks for reporting.
