### ISSUE TITLE
Autocomplete not working on windows

### ISSUE THREAD

**Issue by cahergil** [flowtype/flow-for-vscode#361]
I'm using windows 10 and vscode 1.36 and have installed this great plugin, but it seems that autocompletion is not working.

To test if the issue is a flow or flow-for-vscode issue I have disabled the extension and created the following test file:
```
/* @flow */
type Props = {
  foo: string,
  bar: string,
};

declare var props: Props;

props.
```
 run the following command:

`yarn flow autocomplete 9 7 < path_to_above_file`

being 9 and 7 lines of the file. I got this:

```
bar string
foo string
hasOwnProperty (prop: mixed) => boolean
isPrototypeOf (o: mixed) => boolean
propertyIsEnumerable (prop: mixed) => boolean
toLocaleString () => string
toString () => string
valueOf () => mixed
```
I disabled **use LSP**  VSCode settings 
![log](https://user-images.githubusercontent.com/25084874/64268433-5c968f80-cf38-11e9-9ac2-51b14c9a0c26.png)
and enabled **flow-for-vscode** plugin again.

This time _autocompletion_ seems to be working:

![logok](https://user-images.githubusercontent.com/25084874/64268766-0249fe80-cf39-11e9-9474-d0974ca6031a.png)

The problem is that I have to disable LSP for this,
any idea why is not working with LSP?
Thanks in advanced.

**Comment by mroch** [comment]
what version of Flow? v0.101.0 fixed a bug that sounds like this. I just tested on v0.107.0 (which also has some autocomplete fixes, but I wouldn't expect them to impact this) and it seems to be working.

**Comment by mroch** [comment]
actually I tested on Mac. do you know if this is specific to Windows? I'll give it a shot too.

**Comment by Mayank1791989** [comment]
@mroch It's working fine on linux and mac, the issue is coming on windows only.

**Comment by mroch** [comment]
there are some tests in `newtests/` but i doubt that'd make a difference. wondering if it's a line endings issue or something like that.

**Comment by Mayank1791989** [comment]
I will try on vim on windows to find it's a plugin bug or some issue in flow. As far as I know it used to work fine some time back on windows. Also the flow autocomplete working fine.

**Comment by mroch** [comment]
I can repro on Windows.

The LSP requests look the same on both Mac and Windows:

```
[Trace - 3:49:48 PM] Sending request 'textDocument/completion - (6)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/mroch/Code/playground/test.js"
    },
    "position": {
        "line": 8,
        "character": 6
    },
    "context": {
        "triggerKind": 1
    }
}
```

this is from Mac. on Windows, the uri is "file:///C:/Users/mroch/Documents/Code/playground/test.js" but the rest is the same.

**Comment by Mayank1791989** [comment]
Hmm the request is correct.

**Comment by cahergil** [comment]
> what version of Flow? v0.101.0 fixed a bug that sounds like this. I just tested on v0.107.0 (which also has some autocomplete fixes, but I wouldn't expect them to impact this) and it seems to be working.
flow version is 0.106.1

**Comment by mroch** [comment]
> wondering if it's a line endings issue or something like that.

yup. changing "CRLF" to "LF" in the bottom right makes it work.
