### ISSUE TITLE
Autocomplete fills in function arguments when passing functions by reference

### ISSUE THREAD

**Issue by peterkhayes** [flowtype/flow-for-vscode#363]
This has been an annoying issue with intellisense/autocomplete, given how common passing callbacks is in the Javascript world.

To reproduce, set up a very simple Flow project
```bash
mkdir test && cd test
yes | yarn init
yarn add flow-bin
yarn flow init
touch index.js
code index.js
```

Then type
```javascript
// @flow
const arr = [1, 2, 3];
const double = (x: number) => x * 2;

arr.map(dou
```

The autocomplete will suggest `double`:
![image](https://user-images.githubusercontent.com/3714569/64460613-aeadf100-d0af-11e9-88a8-e1c0e45ef5fa.png)

But when you hit tab/enter, it will fill in the arguments, which is not what we want:
![image](https://user-images.githubusercontent.com/3714569/64460629-b7062c00-d0af-11e9-9275-47a9ff32d20a.png)

I notice that this problem does not occur in the built-in Javascript/Typescript intellisense, and I'm wondering if that could be implemented here as well.

**Comment by Mayank1791989** [comment]
Current implementation of function autocomplete is very simple and it doesn't use context to detect which case is valid. You can disable function autocomplete with  with params using the plugin setting `flow.useCodeSnippetOnFunctionSuggest: false`.

> I notice that this problem does not occur in the built-in Javascript/Typescript intellisense, and I'm wondering if that could be implemented here as well.

It's the same case with typescript. Try the below code with this setting `"typescript.suggest.completeFunctionCalls": true`

```js
const arr = [1, 2, 3];
function double(x: number) { return x * 2; }

arr.map(double(x));
```

**Comment by peterkhayes** [comment]
Thanks, I'll try that for now.
