### ISSUE TITLE
Computing type coverage never ends

### ISSUE THREAD

**Issue by MikeYermolayev** [flowtype/flow-for-vscode#365]
Hello,

I'm trying to run flow with enabled `useLSP` in a multi-root workspace but seems it can't finish type coverage computing.

The loading goes forever...
![image](https://user-images.githubusercontent.com/8783498/64693177-54da6c00-d49f-11e9-8402-e635e78c59fb.png)

![image](https://user-images.githubusercontent.com/8783498/64693285-979c4400-d49f-11e9-8073-18fd0e32afbc.png)

![image](https://user-images.githubusercontent.com/8783498/64693329-af73c800-d49f-11e9-92e1-a795cb3f048f.png)

Flow config looks like this:
![image](https://user-images.githubusercontent.com/8783498/64693382-d205e100-d49f-11e9-963a-8231ffc65fc4.png)

Thanks in advance

**Comment by Mayank1791989** [comment]
@MikeYermolayev Yes this happens sometimes when plugin misses coverage response. It is hard to reproduce so never fixed it. Try switching files in editor it will show you the coverage.

**Comment by MikeYermolayev** [comment]
Switching files didn't help, but after I killed all flow processes from activity monitor, quit vscode instead of reloading window, remove all workspace settings to make sure that  I use defaults, everything started to work. Not really sure what really helped me from above sequence.
Maybe some flow process stuck after turning on LSP.

Anyway, I'm closing the issue until meet it again.
Thanks

**Comment by Mayank1791989** [comment]
@MikeYermolayev Sometimes flow process hangs. I think in your case that happened. You can run `flow stop && flow status` to fix.
