### ISSUE TITLE
TypeScript types inline import syntax support

### ISSUE THREAD

**Issue by Eugene-Musika** [flowtype/flow-for-vscode#367]
Latest versions of VS Code autocompletes types with TypeScript inline imports like so:

types.js
```javascript
  export type Language = 'en' | 'fr';
````

index.js
```javascript
  const language: import('./types).Language = 'en';
```

It would be very handy if this extension and flow itself supports this feature.

**Comment by mroch** [comment]
this would need to be implemented in Flow itself and would then come for free in this extension. would you mind reporting it there instead? unfortunately we can't move the issue since it's across different github orgs.

**Comment by curiousdustin** [comment]
This inline import style is happening to me when I choose to auto-complete and auto-import a flow type. But I don't want it to. I want the import to be inserted at the top of the file.

How can I turn this off?
