### ISSUE TITLE
When using useLSP=true, Flow checks all files regardless of Flow pragma presence

### ISSUE THREAD

**Issue by migueloller** [flowtype/flow-for-vscode#369]
I have a monorepo with TypeScript and Flow projects. I want to turn off errors in JS files that don't have the Flow pragma (`/* @flow */`) but when using LSP, the plugin doesn't seem to follow the `.flowconfig` option of `all=false` as stated in the description of the `useLSP` config. Turning off `useLSP` works, though.

**Comment by Mayank1791989** [comment]
Looks like some issue in flow. Which version of flow are you using?

**Comment by migueloller** [comment]
Using Flow v0.110.0

**Comment by migueloller** [comment]
Running Flow from the CLI doesn't have this issue and respects the `all` option. It seems to be only a VSCode issue when using LSP.

**Comment by Mayank1791989** [comment]
Try using flow 0.109. I think this is a bug introduced recently. See changelog of v0.110.1.

**Comment by Mayank1791989** [comment]
@migueloller I tested locally. It's happening only with flow v0.110. Updating to v0.110.1 will fix your issue.

**Comment by migueloller** [comment]
@Mayank1791989, thanks for checking!

**Comment by Mayank1791989** [comment]
Please close the issue.

**Comment by migueloller** [comment]
Just tried 1.110.1 and the issue is still there.

**Comment by Mayank1791989** [comment]
What is the version of flow showing in status bar of vscode?

**Comment by migueloller** [comment]
Flow version 0.110.1. Here are some screenshots:

![image](https://user-images.githubusercontent.com/5677929/67519845-b46a9080-f675-11e9-8829-1192b05a0519.png)
![image](https://user-images.githubusercontent.com/5677929/67519908-d532e600-f675-11e9-9e30-9fb6e5dfe5dd.png)

Notice that the tooltip shows both TypeScript and Flow information. It should only be showing TypeScript in this case as `all=false` in the `.flowconfig`. It doesn't seem to be going away even with LSP turned off now.

**Comment by migueloller** [comment]
Hmm, errors seem to not be reported properly though so it's only showing type information in the tooltip which is fine. The original issue of it type checking files that it shouldn't seems to be gone now. Thanks!

**Comment by Mayank1791989** [comment]
@migueloller But why autocomplete and other commands working on files without @flow. I always thought it works only if @flow is present.

**Comment by migueloller** [comment]
The type checking isn't there, but VSCode will show type hints from Flow. This is a bit annoying and I wanted to avoid it but it's not as bad as big red squiggles in the file. If you can find a way to have Flow completed disabled for files without the Flow pragma, I would love to know!
