### ISSUE TITLE
Extension not installing properly, keeps showing "Update" button forever.

### ISSUE THREAD

**Issue by kumarharsh** [flowtype/flow-for-vscode#37]
I just installed the flow extension in my vscode-insider 1.6.0, and it's installed some 0.0.3 version, but from the 'releases' page, it seems like the latest release is 0.3.2.

Even though I've just installed the plugin, it keeps showing a **Update** button. After clicking on update, an **Enable** button is also shown alongside the **Update** button, but after restarting vscode, the version of the installed extension doesn't change, and the update button is still shown. This keeps happening no matter how many times I restart vscode. Also, seems like it's only happening with this extension.

![image](https://cloud.githubusercontent.com/assets/760112/18743904/e46275b6-80d8-11e6-98c6-da7830a21b9f.png)

**Comment by wycats** [comment]
I have the same issue; I'm on Windows if that's helpful.

**Comment by kumarharsh** [comment]
Yes, I'm also on Windows. forgot to mention that earlier.

**Comment by gabelevi** [comment]
Does uninstalling and reinstalling work? I'm afraid I'm not too familiar with vscode or what could cause this

**Comment by wycats** [comment]
It's probably related to:

```
$ cat ~/.vscode-insiders/extensions/flowtype.flow-for-vscode-0.3.2/package.json
{
        "name": "flow-for-vscode",
        "version": "0.0.3",
        "publisher": "flowtype",
        "description": "Flow support for VS Code",
        "displayName": "Flow Language Support",
        "engines": {
                "vscode": "0.10.x"
        },
        "categories": [
                "Languages",
                "Linters"
        ],
        "private": true,
        "activationEvents": [
                "onLanguage:javascript"
        ],
        "main": "./build/flowMain",
        "contributes": {
                "grammars": [
                        {
                                "language": "javascript",
                                "scopeName": "source.js.jsx",
                                "path": "./syntaxes/Babel Language.json"
                        },
                        {
                                "scopeName": "source.regexp.babel",
                                "path": "./syntaxes/Babel Regex.json"
                        }
                ],
                "snippets": [
                        {
                                "language": "javascript",
                                "path": "./snippets/flow.json"
                        }
                ],
                "debuggers": [
                        {
                                "type": "extensionHost",
                                "enableBreakpointsFor": {
                                        "languageIds": [
                                                "javascript"
                                        ]
                                }
                        },
                        {
                                "type": "node",
                                "enableBreakpointsFor": {
                                        "languageIds": [
                                                "javascript"
                                        ]
                                }
                        }
                ]
        },
        "scripts": {
                "vscode:prepublish": "./compile.sh",
                "compile": "./compile.sh --watch"
        },
        "dependencies": {
                "nuclide-flow-base": "0.0.35",
                "regenerator-runtime": "^0.9.5"
        },
        "devDependencies": {
                "vscode": "0.10.x",
                "babel-cli": "^6.1.4",
                "babel-plugin-transform-flow-strip-types": "^6.0.14",
                "babel-preset-es2015": "^6.1.4",
                "babel-preset-stage-1": "^6.1.2"
        },
        "icon": "flow-logo.png",
        "repository": {
                "type": "git",
                "url": "https://github.com/flowtype/flow-for-vscode.git"
        },
        "bugs": {
                "url": "https://github.com/flowtype/flow-for-vscode/issues"
        },
        "__metadata": {
                "id": "b3917e4f-5086-4def-a82b-2ae6b708db16",
                "publisherId": "abad690f-9e62-4fc4-a898-a944ea7d94b7",
                "publisherDisplayName": "flowtype"
        }
}
```

Note the version in the package.json.

**Comment by gabelevi** [comment]
@wycats - After publishing 0.3.1 with `vsce publish patch`, I removed the extension, searched the marketplace, found 0.3.1, and installed it. However when I looked at `~/.vscode/extensions/flowtype.flow-for-vscode-0.3.1/package.json`, the `package.json` still said 0.3.0.

So I figured `vsce publish patch` maybe didn't work right, so I manually updated the `package.json` and ran `vsce publish 0.3.2`. Then I removed the extension, searched the marketplace, found 0.3.2, and installed it. However when I looked at `~/.vscode/extensions/flowtype.flow-for-vscode-0.3.2/package.json`, the `package.json` now said 0.3.1

So now I figured that the marketplace had some bad caching bug. I waited for a bit, uninstalled, and reinstalled 0.3.2. Now, the package.json was right.

However it's really worrying if you're seeing something similar :(

**Comment by gabelevi** [comment]
On OSX, if I uninstall "Flow Language Support" and search on the market, I do find 0.3.2. If I install it and check `~/.vscode/extensions/flowtype.flow-for-vscode-0.3.2/package.json`, it does say version 0.3.2.

Does a fresh install of the extension on Windows still install an old version?

**Comment by kumarharsh** [comment]
I just tried it, and it seems that it's not working on a fresh install of the extension too. The version is still 0.0.3

**Comment by gabelevi** [comment]
What version of vscode do you guys use? Looking at the `package.json` for this extension, I see that the extension claims it only works with vscode `1.5.x`. Maybe this should be `^1.3.0` or something like that. I'm actually not sure what the minimum version should be.

However, if I install vscode 1.3.0 and install this extension, I get

```
$ grep version ~/.vscode/extensions/flowtype.flow-for-vscode-0.0.3/package.json 
        "version": "0.0.3",
```

which is similar to what you guys are reporting, but the extension's directory is 0.0.3 instead of 0.3.2.

**Comment by kumarharsh** [comment]
I'm using vscode insider 1.6.0. To clarify, I'm seeing the 0.3.2 version **before** installing flow-for-vscode, but after installing (and restarting vscode), it shows 0.0.3 and those "Update" and "Install" buttons.
