### ISSUE TITLE
Intellisense not suggesting basic types

### ISSUE THREAD

**Issue by deepakaggarwal7** [flowtype/flow-for-vscode#370]
**flow-bin**: 0.106.0 (installed globally and works from terminal)
**.flowconfig**: exists in root of project folder
**OS**: Mac Mojave
**VSCode**: 1.39.2
**Builtin TS/JS plugin**: disabled for workspace
**vsplugin - Flow Language Support** - 1.5.0
**vsplugin - Babel JavaScript** -  0.0.25

**Problem**
Flow works by displaying errors but doesn't show intellisense for default types which makes it difficult to use flow. In the following capture, I would expect "string" to be suggested as I start typing  **st**

I've spent a few days now to make it work. What additionally should I do to get the intellisense?

![Image of Yaktocat](https://i.imgur.com/tXrCcS0.gif)

**Comment by alikazemkhanloo** [comment]
This is actually frustrating when IntelliSense autocorrects `string` with `String`. I have to press `ESC` to prevent that.
