### ISSUE TITLE
Add support for flow-parser?

### ISSUE THREAD

**Issue by FezVrasta** [flowtype/flow-for-vscode#383]
Hi, would it be possible to add support for the [flow-parser](http://npmjs.com/flow-parser) package? It would allow to run Flow without the OS-specific binary.

It would be a great way to make this extension work on "cloud versions" of VS Code, such as CodeSandbox, and Visual Studio Online (I don't have experience with the latter though).

I'd be happy to contribute to the feature if it's something you think would be valuable.

**Comment by orta** [comment]
Hi!

This library only supports making an AST from a flow file, but leaves the developer experience  via the [LSP](https://microsoft.github.io/language-server-protocol/) out. Maybe you could try make a similar project which extracts out their LSP support?

**Comment by FezVrasta** [comment]
Hi, thanks for the quick answer.

May you help me understand what you mean with "only supports making an AST from a flow file"?

My idea was to add `flow-parser` as an alternative, but rather than reading directly from the file system, it would get the code from the VSCode APIs, which should be pretty much what happens with the built-in TS extension.

**Comment by TrySound** [comment]
flow-parser is what package name says. It does not do any checks or autocompletions. Adding it to extension may only help with not failing on invalid syntax.

**Comment by FezVrasta** [comment]
I didn't get it, now it makes sense, I thought it was the same package used by the Flow online playground.

Do you know what they user there then?

**Comment by TrySound** [comment]
They compile ocaml to js. Though result is playground specific, does not include many features and very slow for development. JS is not very efficient compared to native.
