### ISSUE TITLE
Errors are reported for files with `// @noflow` comment

### ISSUE THREAD

**Issue by kevinbarabash** [flowtype/flow-for-vscode#384]
Running flow manually on the command line does not report errors in files with `// @noflow` comments, but the `flow-for-vscode` plugin does report errors.  This appears to be an LSP only issue since disabling the LSP fixed the issue..  I'm running flow 0.110.0.

**Comment by orta** [comment]
This should probably be upstreamed to flow's issues, I don't think it's the responsibility of the extension to keep track of the comment to enable/disable on a per-file basis

**Comment by mroch** [comment]
I can't repro this using flow v0.159.0 and flow-for-vscode 1.9.2 in LSP mode.
```
// @noflow
(123: string); // no error
```
but changing it to @flow finds the error.

if it's still an issue, please file an issue in the facebook/flow repo (good suggestion @orta)
