### ISSUE TITLE
Flow doesn't work with react native project

### ISSUE THREAD

**Issue by xcaluca** [flowtype/flow-for-vscode#388]
When I tried to start a new project with React Native, it always appears the same error message.   

![error](https://user-images.githubusercontent.com/57778245/82272146-24ad6c00-9950-11ea-86e9-13a378f82eec.PNG)

I'm doing this every time:
`react-native init AwesomeProject`
And when I open the project in VSCode, the error appears!

**Comment by orta** [comment]
follow the setup instructions in the README to solve this: https://github.com/flowtype/flow-for-vscode#setup
