### ISSUE TITLE
Autocomplete of primitives when defining types keeps PascalCasing

### ISSUE THREAD

**Issue by Brianzchen** [flowtype/flow-for-vscode#390]
Whenever I want to type a primitive type, vscode will autocomplete to PascalCase which is really annoying
eg: `string -> String`, `number -> Number`, `boolean -> Boolean`.

Here's an example if I'm creating a new Props type
<img width="773" alt="Screen Shot 2020-05-26 at 11 39 10 am" src="https://user-images.githubusercontent.com/12436524/82852502-810f1d80-9f46-11ea-89db-6cf9de9f3e62.png">

When I type `,` because I want to add another type or because I like trailing commas, it autocompletes and changes to
<img width="647" alt="Screen Shot 2020-05-26 at 11 39 17 am" src="https://user-images.githubusercontent.com/12436524/82852546-95ebb100-9f46-11ea-8743-33b5cd770fd5.png">

I believe this is caused by 
<img width="373" alt="Screen Shot 2020-05-26 at 11 45 43 am" src="https://user-images.githubusercontent.com/12436524/82852485-748ac500-9f46-11ea-9a15-884d5ed87611.png">

But I don't want to turn this off otherwise I lose some import path suggestions and will ruin my dev experience.
Is there any fix for this or can `number`/other primitives be added to flow as one of the auto complete suggestions so that vscode auto completes to the lowercase suggestion?

**Comment by mroch** [comment]
thanks for the report, this is indeed super confusing. 

primitive type suggestions are added in https://github.com/facebook/flow/commit/d45ca1994cfa3a98c238959e228db414318b9490 and will be in flow 0.161.

if there are other features making you want to leave JavaScript > Suggest enabled, please file issues on the facebook/flow repo!
