### ISSUE TITLE
Wrong suggestions while spreading object entries

### ISSUE THREAD

**Issue by seahindeniz** [flowtype/flow-for-vscode#394]
Hi

This issue is related to the issue #171. Since it has posted and closed for a long time ago, I would like to add few questions to get addressed.
_Excuse me if I'm doing this wrong._

---
Typescript plugin is kind of very useful where Flow suggestions are insufficient. Typescript has a good intellisense when it comes to and that is why it is kind of important to use both at the same time.

Typescript plugin disabled
![image](https://user-images.githubusercontent.com/5789670/89052169-fa1f5c80-d35d-11ea-99f5-65f8d3d4298a.png)

Enabled
![image](https://user-images.githubusercontent.com/5789670/89052280-263add80-d35e-11ea-8a98-79bbb7737247.png)

These are just a small examples where they both are very useful and also crucial to use it together. FLS suggests things where Typescript extension can't and Typescript extension suggests things where FLS can't.

- Can't the extension push the expected suggestions to the suggesting list,
- and can't it suppress the wrong suggestions where posted in the issue #171? It would be good to have.

_First one is already enough to continue_

**Comment by orta** [comment]
The thing is that both plugins cover the same grounds, and from the flow plugins perspective it does not know about the typescript support. So, it can only clash with the TS version when it has results.

Perhaps the Flow extension could also run a copy of the typescript extension and remove duplicates, but that's gonna be brittle code I bet. Your best bet is to try improve either this extension, or the flow LSP in flow to get some sense of feature parity.

**Comment by mroch** [comment]
thanks for the feedback. improving the Flow LSP to get feature parity is indeed the way to go IMO. we added autocomplete for globals in 0.156 (and experimentally starting in 0.143 with `autoimports=true` in your flowconfig), which handles this case:

<img width="556" alt="Screen Shot 2021-09-10 at 9 52 07 AM" src="https://user-images.githubusercontent.com/3012/132864509-71d86e90-b408-4916-924e-0c20aade4001.png">
