### ISSUE TITLE
No extension

### ISSUE THREAD

**Issue by Aslemammad** [flowtype/flow-for-vscode#397]
I can't find the vs code extension( codium), even if I try installing it from the command line, it says not found. Please solve it ASAP. Thanks.

**Comment by achrinza** [comment]
Taken from the VSCodium GitHub readme:

> According to the VS Code Marketplace Terms of Use, you may only install and use Marketplace Offerings with Visual Studio Products and Services. For this reason, VSCodium uses open-vsx.org, an open source registry for VS Code extensions.

[Open VSX](https://open-vsx.org/) is managed by the Eclipse Foundation to compliment Eclipse Theia, their own code editor based on Visual Studio Code.

Hence, the flowtype team would need to co-publish the extension to Open VSX for it to appear.
