### ISSUE TITLE
Status bar icon with file and flow server status

### ISSUE THREAD

**Issue by Arilas** [flowtype/flow-for-vscode#40]
When user open new Project that need flow server to start user don't have information about server startup and his status. I suggest to implement status bar icon wit tooltip like "Server starting", "No errors", "Failed to start flow server", etc

Also we can use this icon to notify user about problems in current file(so user can quickly check only it without errors from some linters, etc)

VSCode has API for this - `createStatusBarItem` and also `setStatusBarMessage`(which support Promise as a parameter so we can show flow server start for example).

**Comment by davertron** [comment]
Yeah, I'm currently running into issues where the flow checking stops working (don't know why yet...) but I have no idea because there's no status anywhere saying whether it ran successfully or just failed.

**Comment by orta** [comment]
#55 will give an output channel for any errors, so it should make it a lot easier to know if something is up - and why.  

I'm open to adding a status bar similar to what I have in [vscode-jest](https://github.com/orta/vscode-jest)

**Comment by Mayank1791989** [comment]
fixed in b5be6578a7a51dfb4e38db4c2f1a1ad41c3afb82. Try v1.1.0.
