### ISSUE TITLE
syntax highlighting edge case

### ISSUE THREAD

**Issue by mf-alex-tsepkov** [flowtype/flow-for-vscode#400]
The following valid JS syntax causes the syntax highlighter to freak out:
```
let [foo, bar] = someString.split(':');
```
The wrong highlighting starts at the square bracket and the plugin never recovers afterwards. Basically, it seems like array-unpacking syntax confuses the plugin into thinking that I'm defining a type when I'm not.

**Comment by mroch** [comment]
this extension doesn't provide syntax highlighting. not sure where the bad highlighting would be coming from, sorry. both VS Code's default highlighter and [vscode-language-babel](https://github.com/michaelgmcd/vscode-language-babel) (the extension i'd recommend for highlighting Flow) seem to support this.
