### ISSUE TITLE
Cant get flow type support.

### ISSUE THREAD

**Issue by amandamaharjan** [flowtype/flow-for-vscode#407]
I get the following error.

[admin-portal/.flowconfig] Failed to start flow
Error: Flow version 0.72.0 doesn't support 'flow lsp'. Please upgrade flow to version >=0.75.

I tried updating flow-bin to 0.75 but to no avail

**Comment by mroch** [comment]
after updating flow-bin, try "Flow: Reload Client" from the command palette to get it to try using the new version. also, if your `.flowconfig` has a `[version]` section, make sure to update that too.
