### ISSUE TITLE
Wrong info on mouse over for the exact types

### ISSUE THREAD

**Issue by ggregoire** [flowtype/flow-for-vscode#42]
Example:

``` javascript
type State = { user: User };
```

On mouse over: `type State = { user: {...} }` => OK

``` javascript
type State = {| user: User |};
```

On mouse over: `type State = any` => NOK
## 

I use the latest versions of vscode and flow.

**Comment by orta** [comment]
I think what you're seeing is the typescript hovers: https://github.com/flowtype/flow-for-vscode/issues/50

See when I hover normally its an `any` when when I hold cmd to do all annotations, you see it

![2016-12-29 15_42_03](https://cloud.githubusercontent.com/assets/49038/21554427/6d1958f6-cddd-11e6-94de-fa7a83ab059d.gif)
