### ISSUE TITLE
Extension crashes when using `flow-bin` 1.151.0 in project

### ISSUE THREAD

**Issue by vanstinator** [flowtype/flow-for-vscode#425]
The extension is crashing when loading the `SHASUM256.txt.sign` file to validate the flow binary in node_modules. It appears the file extension has changed to purely `.txt` and the extension doesn't account for that.

```
ENOENT: no such file or directory, open '/home/justin/projects/plexamp-native/node_modules/flow-bin/SHASUM256.txt.sign'
```

**Comment by vrama628** [comment]
Hi @vanstinator, could you let me know what output you see when you set `Settings->Flow Configuration->Flow: Log Level` to `trace` then open `View->Output` and select `Flow` from the dropdown menu on the Output pane, and open VSCode to a Flow project.

For context, it is expected that `flow-bin` versions 0.153.0 and earlier will not contain a file `SHASUM256.txt.sign`, and we have error handling that is specifically meant to handle that, so it's unexpected that this is causing the extension to crash.

**Comment by mroch** [comment]
please reopen if still an issue

**Comment by frednomoon** [comment]
this is still an issue for me. the output channel looks like this ```
[Info  - 1:20:50 PM - x/.flowconfig] restarting client
[Info  - 1:20:50 PM - x/.flowconfig] Unable to verify SHASUM256.txt.sign:
ENOENT: no such file or directory, open '/Users/x/.../node_modules/flow-bin/SHASUM256.txt.sign'
[Info  - 1:20:50 PM - x/.flowconfig] Found flow using option `useNPMPackagedFlow`
[Info  - 1:20:51 PM - x/.flowconfig] Using flow '/Users/x/.../node_modules/flow-bin/flow-osx-v0.108.0/flow' (v0.108.0)
Launching Flow server for /Users/x/...
Spawned flow server (pid=94085)
....
[Info  - 1:20:51 PM] Starting Flow server
```

**Comment by frednomoon** [comment]
Actually I dont think the SHASUM bit is the problem though because it continues to start the server. And then a few seconds later it crashes with no logs
