### ISSUE TITLE
Using Array<T> yield incorrect highlightning

### ISSUE THREAD

**Issue by ptomasroos** [flowtype/flow-for-vscode#43]
Thanks for a great plugin.
See screenshots.

First example works

![screen shot 2016-10-10 at 11 09 45](https://cloud.githubusercontent.com/assets/1064547/19231391/1a8a2120-8eda-11e6-97ff-13f7dee09d3f.png)

Second does not yield a good syntax highlightning
![screen shot 2016-10-10 at 11 09 37](https://cloud.githubusercontent.com/assets/1064547/19231392/1aa40f5e-8eda-11e6-8ee2-59befdcac92d.png)

**Comment by levito** [comment]
Installing this standalone syntax extension solves the problem:
https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring

**Comment by orta** [comment]
I think this is fixed in the new JS grammar from Microsoft - https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

![screen shot 2016-12-06 at 16 28 27](https://cloud.githubusercontent.com/assets/49038/20933818/1cc06098-bbd1-11e6-8054-8a33dba420c5.png)
