### ISSUE TITLE
I'm used babel-plugin-module-resolver cannot resolve module in vscode.

### ISSUE THREAD

**Issue by viweei** [flowtype/flow-for-vscode#430]
flow with babel-plugin-module-resolver is work well in shell，but plugin of flow-language-support in vscode cannot resolve module.

it's screenshot in vscode
![image](https://user-images.githubusercontent.com/1762036/133183031-10a9734e-6d6f-444f-9a1b-4a3023e79a50.png)

but nothing error in shell.
![image](https://user-images.githubusercontent.com/1762036/133183482-084adac2-20d0-4139-b27c-3c666898171e.png)

I were changed  "@/store" to "./store", it does worked well.
![image](https://user-images.githubusercontent.com/1762036/133183289-7ada9824-1ed4-467e-ab24-48b64d11b1fe.png)

here are config file of .babelrc and .flowconfig

.babelrc
```json 
{
  "presets": ["@babel/preset-flow", "@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-runtime",
    [
      "module-resolver",
      {
        "root": ["src"],
        "extensions": [".js", ".jsx"],
        "alias": {
          "@": "./src"
        }
      }
    ]
  ]
}
```

.flowcofnig
```ini
[ignore]

[include]

[libs]
flow-typed/

[lints]

[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src

[strict]

```

**Comment by noppa** [comment]
This a problem in your Flow configuration and not an issue in the VSCode extension. If you run `flow check` on the command line, I bet that doesn't work correctly either.

In this case, you need something like
```
module.name_mapper='^@/\(.*\)$' -> '<PROJECT_ROOT>/src/\1'
```
in the flowconfig `[options]`. See [name_mapper in the options docs](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string).

**Comment by mroch** [comment]
it looks like `yarn flow ./src` should've checked all the files, since there's no lazy mode. so then my question is why the CLI missed it...

unless the squiggle in vscode is actually from the built-in typescript/javascript language support?

**Comment by viweei** [comment]
@noppa  Yes~ I had appended 
> module.name_mapper='^@/\(.*\)$' -> '<PROJECT_ROOT>/src/\1'

 to section end of  options and restart vscode then it worked.  Thanks~ 👍

**Comment by viweei** [comment]
@mroch    Are you mean  `javascript.validate.enable` and `typescript.validate.enable`  options ?  I already set them value were false, but it had error yet.
