### ISSUE TITLE
flow vscode plugin is not working anymore on version 1.6.0 (latest)

### ISSUE THREAD

**Issue by Alexisvt** [flowtype/flow-for-vscode#44]
Hi I just update my vscode to v1.6.0 and now the flow plugin stop working! I already test the flow cli and is working correctly, is checking my files and is finding errors, but the plugin doesn't, thanks!

My flow version is the latest (v0.33.0)

**Comment by ajhyndman** [comment]
I've submitted a PR which addresses this, for consideration!

#45 

(For anyone looking for a workaround, updating the vscode version in this extension's package.json will resolve this.)

**Comment by Alexisvt** [comment]
Hi, I changed the version on the package.json of the plugin and It didn't works, this is how it looks
after the change:
```json
{
	"name": "flow-for-vscode",
	"version": "0.0.3",
	"publisher": "flowtype",
	"description": "Flow support for VS Code",
	"displayName": "Flow Language Support",
	"engines": {
		"vscode": "1.6.0"
	},
	"categories": [
		"Languages",
		"Linters"
	],
	"private": true,
	"activationEvents": [
		"onLanguage:javascript"
	],
	"main": "./build/flowMain",
	"contributes": {
		"grammars": [
			{
				"language": "javascript",
				"scopeName": "source.js.jsx",
				"path": "./syntaxes/Babel Language.json"
			},
			{
				"scopeName": "source.regexp.babel",
				"path": "./syntaxes/Babel Regex.json"
			}
		],
		"snippets": [
			{
				"language": "javascript",
				"path": "./snippets/flow.json"
			}
		],
		"debuggers": [
			{
				"type": "extensionHost",
				"enableBreakpointsFor": {
					"languageIds": [
						"javascript"
					]
				}
			},
			{
				"type": "node",
				"enableBreakpointsFor": {
					"languageIds": [
						"javascript"
					]
				}
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "./compile.sh",
		"compile": "./compile.sh --watch"
	},
	"dependencies": {
		"nuclide-flow-base": "0.0.35",
		"regenerator-runtime": "^0.9.5"
	},
	"devDependencies": {
		"vscode": "1.6.0",
		"babel-cli": "^6.1.4",
		"babel-plugin-transform-flow-strip-types": "^6.0.14",
		"babel-preset-es2015": "^6.1.4",
		"babel-preset-stage-1": "^6.1.2"
	},
	"icon": "flow-logo.png",
	"repository": {
		"type": "git",
		"url": "https://github.com/flowtype/flow-for-vscode.git"
	},
	"bugs": {
		"url": "https://github.com/flowtype/flow-for-vscode/issues"
	},
	"__metadata": {
		"id": "b3917e4f-5086-4def-a82b-2ae6b708db16",
		"publisherId": "abad690f-9e62-4fc4-a898-a944ea7d94b7",
		"publisherDisplayName": "flowtype"
	}
}

```

**Comment by Alexisvt** [comment]
Im not seeing any intellisense (Flow one)  that I had on the past and It doesn't show any errors on the code, but If I run the flow command on my code, it show me the errors on it

**Comment by Alexisvt** [comment]
Thanks dude, it works, I double check my package.json file and I found something odd, and I discovered that I had an older version of the plugin, after update the plugin, my package.json look identical to the master one, I change the number as your push request do and it's back to life!! Awesome!

**Comment by OlegZee** [comment]
VSCode now installs v0.0.3 despite the version it shows in the list of available plugins.
This 0.0.3 does not seem to work at all.

**Comment by Alexisvt** [comment]
Yes that's true, what I did was to do a downgrade to vscode, I choosed the version before the latest, then vscode notify me that I have an older version of flow for vs code, I update the plugin and I get the latest (the one that is on this repo), after that I update again vscode, and did the workaround that @ajhyndman provide and it works!

**Comment by IlyaSV** [comment]
Alexisvt, thanks - it helped.

**Comment by vedmalex** [comment]
just have to clone this repository into .code/extensions
```
npm i && ./compoile.sh
```
and it is working like a charm!

We also need this #45 update

**Comment by grisevg** [comment]
I never used flow with vscode, so I'm not sure if flow errors should be highlighted in source files or be listed in errors and warning window.
I cloned the latest master (068defc) and compiled it, but flow errors didn't start to show up for me.
I do get tooltips with the deduced flow type now, which I didn't get with latest released version.
![image](https://cloud.githubusercontent.com/assets/155348/19497039/297f9c92-9582-11e6-94f5-a5c5f082abc7.png)

**Comment by Alexisvt** [comment]
You should see red lines on your editor something is wrong with the extension please review the workaround and check again

**Comment by grisevg** [comment]
I did try the latest master with `^1.4.0` engine version and tried to manually change it to `1.6.1`. 
Neither made errors to show up in my code.

What's the best way to debug it?

**Comment by Alexisvt** [comment]
Hi, the actual version (master) should make vscode works correctly since they are using range (^1.4.0) I have that version installed and everything is working correctly. Try to follow the steps on  [flow for visual studio code plugin page](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode) to see if you are missing something, the latest version should fix the issue with the newest version of vscode

**Comment by ajhyndman** [comment]
Thanks for the update @Alexisvt!
