### ISSUE TITLE
Extension don't support flow comments syntax

### ISSUE THREAD

**Issue by olegdeezus** [flowtype/flow-for-vscode#46]
![image](https://cloud.githubusercontent.com/assets/3694749/19350231/9d2c8046-915f-11e6-99ed-412688cf0fda.png)

VS

![image](https://cloud.githubusercontent.com/assets/3694749/19350258/b12efaba-915f-11e6-9b2f-b8d67540852e.png)

**Comment by orta** [comment]
I think we'd have to ship a custom tmlanguage to support this, IMO, it's not worth the extra maintenance to do so, given how tough it is to get one right when there are already a bunch of people working on JS ones.

**Comment by orta** [comment]
Looked at this again

I'm seeing support working on our projects:

![screen shot 2016-12-29 at 3 37 03 pm](https://cloud.githubusercontent.com/assets/49038/21554318/b0077658-cddc-11e6-9e5c-c38063621baf.png)

![screen shot 2016-12-29 at 3 37 42 pm](https://cloud.githubusercontent.com/assets/49038/21554328/c280bd30-cddc-11e6-9e39-e5ada55a75f9.png)

Could it be your project setup?

**Comment by frux** [comment]
Hi! Yes it's working. But it will be marvelous if it also color such comments. Is it possible?

**Comment by orta** [comment]
We don't ship the language support for JavaScript:

> I think we'd have to ship a custom tmlanguage to support this, IMO, it's not worth the extra maintenance to do so

It will need to be added to https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar - I'd recommend asking them 👍

**Comment by Mayank1791989** [comment]
see https://github.com/flowtype/flow-for-vscode#known-issues
