### ISSUE TITLE
Errors list sometimes links to "See:" annotation sites, not actual error sites

### ISSUE THREAD

**Issue by ilkka** [flowtype/flow-for-vscode#48]
For one project of mine, `flow check` outputs:

```
src/controllers/auth.js:49                                                                                                                                             
 49:   server.route(route.createPostRoute('/login', 'auth', {                                                                                                          
                    ^ call of method `createPostRoute`                                                                                                                 
 33:   config: RouteConfiguration                                                                                                                                      
               ^^^^^^^^^^^^^^^^^^ property `tags`. Property not found in. See: src/utils/route.js:33                                                                   
 49:   server.route(route.createPostRoute('/login', 'auth', {                                                                                                          
                                                            ^ object literal
```

The issue is totally valid, but the problem is that when I look at my Errors listing, it mixes up the "see also" and the actual error sites:

<img width="775" alt="screen shot 2016-10-24 at 11 03 35" src="https://cloud.githubusercontent.com/assets/1549/19637839/9a545be6-99d9-11e6-83df-4e0d2842dc4f.png">

Instead of leading to `src/controllers/auth.js`, clicking on that errors leads me to where `createPostRoute` is defined, which is not helpful.

**Comment by gabelevi** [comment]
Would https://github.com/flowtype/flow-for-vscode/pull/47 fix this for you? It adds an error for each file mentioned in a Flow error.

**Comment by ilkka** [comment]
Yeah, I reckon it would! And if the entries appear in order, it would ensure the actual error site comes first in the list which is nice.

**Comment by orta** [comment]
#47 won't fix this I think, it would still show just one error.

in https://github.com/Microsoft/vscode/issues/1927#issuecomment-224229138 they show that you can have a multi-line description, but only with one line showing in the "problems" section. 

So perhaps that is the key
