### ISSUE TITLE
Diagnostics: sometimes it errors with "Invalid JSON result from flow status"

### ISSUE THREAD

**Issue by bpasero** [flowtype/flow-for-vscode#5]
Sometimes the call to find diagnostics results in this error:

[Plugin Host] [2015-11-19T07:47:47.364Z] [ERROR] nuclide - Invalid JSON result from flow status --json /Users/bpasero/Development/Microsoft/vscode-flow/lib/flowDeclaration.js. JSON:
''.

**Comment by frogcjn** [comment]
See https://github.com/facebook/nuclide/pull/512
