### ISSUE TITLE
Adopt SnippetString API

### ISSUE THREAD

**Issue by jrieken** [flowtype/flow-for-vscode#51]
With the December release VS Code will have real API to define a CompletionItem that is inserted as snippet, for details see https://github.com/Microsoft/vscode/issues/3210. 

In short, we now support a subset of the more common TextMate syntax: `$1`, `$2` etc define tabstops, `${1:value}` and `${2:this is${3:nested}}` placeholders, and `$0` is for the final tabstop. 

The API for this is contained in a new type [`SnippetString`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2035). It can be used as the `insertText` of a [CompletionItem](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2364).

During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now).

**Comment by orta** [comment]
Looks like it's this line - https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowCompletion.js#L51

**Comment by jrieken** [comment]
Yeah, looks like the code just needs to be removed
