### ISSUE TITLE
Improve contribution guide - include "how to debug" hints

### ISSUE THREAD

**Issue by SaboteurSpk** [flowtype/flow-for-vscode#59]
I would like to contribute to this extension, but I'm not able to debug it while it's running in host, because it uses babel and custom compile task

Can You please record some video or other guide with hints, how to successfully add breakpoint and watch variables?
Thank You

**Comment by orta** [comment]
I've just sent a PR that addresses this, it's a task that you can start in VS Code - the PR makes it a pre-requisite of running the debugger.

**Comment by SaboteurSpk** [comment]
Hmm, as long as I understand Your PR, You make the babel watcher run before te execution of VS Code in one command.
I had the problem when I manualy started the Babel watch (as described in documentation) and breakpoints didn't work. Now the problem is gone (And I don't know why - probably some version collision or ... )

**Comment by orta** [comment]
Weird! Not sure what was up there then

**Comment by SaboteurSpk** [comment]
Maybe some ghost... It seems that it's working now. Closing this issue and thanx for your time
