### ISSUE TITLE
Interface to nuclide-flow-base is bad

### ISSUE THREAD

**Issue by nmote** [flowtype/flow-for-vscode#6]
- Everything we need should be pre-transpiled.
- Nothing in the interface should be specific to Atom.

**Comment by orta** [comment]
@nmote this still valid?

**Comment by nmote** [comment]
Sort of. `nuclide-flow-base` hasn't been maintained as a standalone npm package in about a year now. Currently code is just copied wholesale from Nuclide from the `nuclide-flow-rpc` folder. But, I guess the interface to that code is still pretty bad, although I did recently make the autocomplete interface less Atom-specific. Obviously at this point we aren't going to get it pre-transpiled.

Anyway, I guess although the situation is far from ideal there's nothing really actionable about this task. Feel free to close.
