### ISSUE TITLE
Uncaught Exception:  TypeError: Cannot read property 'nameOrSourceURL' of undefined

### ISSUE THREAD

**Issue by nonameolsson** [flowtype/flow-for-vscode#67]
This extension has worked perfectly up until recently. Now VS Code is complaining about it all the time. I have uninstalled it and installed it again, but the problem remains.

This is a part of the error message.
```
Uncaught Exception:  TypeError: Cannot read property 'nameOrSourceURL' of undefined
TypeError: Cannot read property 'nameOrSourceURL' of undefined
```

And here is the complete log message.
<img width="1389" alt="index_ios_js_-_cdab_scanr" src="https://cloud.githubusercontent.com/assets/1493018/21740572/6628106e-d4bd-11e6-8440-c1f36c6f5fe2.png">

Am I the only one experiencing this? It has happend on both Windows 10 and MacOS Sierra.

**Comment by orta** [comment]
Can you please try this with 0.5.0 - there were some changes around this area

**Comment by Mayank1791989** [comment]
Closing not happening with new version of plugin.
