### ISSUE TITLE
Flow runs infinitely consuming all memory on my mac

### ISSUE THREAD

**Issue by pronebird** [flowtype/flow-for-vscode#73]
Hi,

I have this funny problem with flow, it seems it goes into some sort of recursion forcing `kernel_task` to consume over 10GB of RAM and creating 50GB swap. At this point my mac goes pretty crazy and asks me to kill some apps.

`sudo fs_usage` reveals that flow reads from disk continuously.

After half an hour my mac turns into jet making funny noise like I am playing AAA video game, but I am just editing javascripts.

I am not sure if that's the problem with flow or the plugin. Disabling plugin resolved the problem.

<img width="777" alt="screenshot 2017-02-01 10 34 50" src="https://cloud.githubusercontent.com/assets/704044/22503606/6bc44d10-e86a-11e6-859c-512783187cdc.png">

<img width="885" alt="screenshot 2017-02-01 10 29 59" src="https://cloud.githubusercontent.com/assets/704044/22503435/a82c4e16-e869-11e6-9b41-35d5b432ed82.png">

**Comment by orta** [comment]
I think you might want to raise this on the flow repo itself?

**Comment by pronebird** [comment]
@orta not sure if the problem is in plugin that mistakenly spawns flow processes or flow itself has some bug...

**Comment by pronebird** [comment]
Reposted on https://github.com/flowtype/flow-typed/issues/643
