### ISSUE TITLE
Feature: Validation enhancement needed

### ISSUE THREAD

**Issue by Alphapage** [flowtype/flow-for-vscode#8]
For now, flow validation occurs only when the file is saved.
It would be great to get a quick validation without saving the file, maybe after a key pressed.

I think you don't implement such a feature because it could take a lot of time or resources.
But I think this could be done when no key are pressed during 3 seconds for example and cancel the job when a key is pressed.
Maybe add a config option to enable the feature?

I hope this could help others.

**Comment by nmote** [comment]
Yes, we plan to add this feature. Flow supports checking the contents of a single unsaved file, but changes to that file will not affect the errors reported in downstream files. I have a bit of work to do to get this to work gracefully but it is definitely on my to do list.
