### ISSUE TITLE
node-modules version of flow doesn't work for windows

### ISSUE THREAD

**Issue by Async0x42** [flowtype/flow-for-vscode#80]
For windows, we use flow-bin, which this extension can't find, I think this is looking for 'flow'. It'd be great if windows was supported as well.

**Comment by orta** [comment]
This should be fixed buy 0.5.0 which was shipped today 👍

**Comment by Amitkmphasis** [comment]
@orta I installed the extension and updated my npm flow-bin. This is my settings.json 

 "flow.useNPMPackagedFlow": true,
  "eslint.autoFixOnSave": true,
  "typescript.validate.enable": false,
  "javascript.validate.enable": false,

I tried restarting the application for error message but there was none.
