### ISSUE TITLE
Do not require global Flow

### ISSUE THREAD

**Issue by polizz** [flowtype/flow-for-vscode#81]
We do not use Flow in every project and even the ones where we do, it's not a global dependency - it's installed local every time. Thus, we get this error a lot when opening any project. Please consider making the global check fail gracefully.

<img width="1013" alt="screen shot 2017-02-14 at 9 26 14 am" src="https://cloud.githubusercontent.com/assets/10888433/22935265/b1a29314-f297-11e6-834d-bfb4db7c6fc2.png">

**Comment by orta** [comment]
I think it would make sense to add a recursive backwards check for a `.flowconfig` through the folders from the current working directory [here](https://github.com/flowtype/flow-for-vscode/blob/master/lib/flowMain.js#L37) before then allowing the extension to activate 👍

**Comment by alexdevico** [comment]
@polizz as workaround you can disable flow extension in "User Settings" and enable it in "Workspace Settings" for projects that require it. Or disable it for some projects (if most of projects require flow)

Currently extension doesn't check that it's required for project or not.
