### ISSUE TITLE
Annotated arrow function with optional breaks highlighting of keywords.

### ISSUE THREAD

**Issue by Naddiseo** [flowtype/flow-for-vscode#90]
The highlighter seems to not work after an arrow function is annotated with an optional return type. In the attached screenshot, you can see that `const`/`let`/`return` in the same scope as the arrow function are highlighted incorrectly.

VSCode: Version 1.10.2

![screenshot from 2017-03-16 12-38-32](https://cloud.githubusercontent.com/assets/115951/24012971/84d40758-0a45-11e7-885e-e803674f41d0.png)

**Comment by orta** [comment]
This extension doesn't provide a syntax highlighter - so it's likely an issue with the default JS highlighter in VS Code, I'd recommend making an issue there 👍

**Comment by Naddiseo** [comment]
[Done](https://github.com/Microsoft/vscode/issues/22764), thanks for the response.
