### ISSUE TITLE
Type cast after destructuring breaks syntax highlighting

### ISSUE THREAD

**Issue by Naddiseo** [flowtype/flow-for-vscode#93]
- VSCode Version: Version 1.10.2
- OS Version: Ubuntu 16.04
- The issue is reproducible regardless of which extensions are enabled; tried with and without `--disable-extensions` 

Steps to Reproduce:
```js
function Test(things) {
	const { e } = (things: Object);
	return '' + e;
}
Test({});
```
![screenshot from 2017-03-20 17-19-42](https://cloud.githubusercontent.com/assets/115951/24126079/a12ee144-0d91-11e7-9520-e3465f9db701.png)

As per the now closed [VSCode bug](https://github.com/Microsoft/vscode/issues/22919#issuecomment-287932246), is this something that `flow-for-vscode` can fix?

**Comment by orta** [comment]
No IMO

Unless someone really wants the maintenance burden of handling creating a flow-specific JS language and keeping it up to date. That's non-trivial.

**Comment by vith** [comment]
It's not specific to destructuring assignments, any type cast expression with parenthesis I try breaks the syntax highlighting on following lines.

I tried the "JavaScript Atom Grammar" suggested in the README and it's even worse; type definitions aren't highlighted even without any assertions around.

:fire:
:floppy_disk:

**Comment by Mayank1791989** [comment]
see https://github.com/flowtype/flow-for-vscode#known-issues
