### ISSUE TITLE
No type hints for flow comments

### ISSUE THREAD

**Issue by mleg** [flowtype/flow-for-vscode#96]
**Type hints** don't appear if types are annotated with flow **comments**.  
It's really frustrating, since in our Node projects we don't have any build step in the workflow. And I believe such setup is pretty common.
![image](https://cloud.githubusercontent.com/assets/7266431/24284863/72ded8c2-107e-11e7-9903-afbe72ca9806.png)
![image](https://cloud.githubusercontent.com/assets/7266431/24285233/4169f8ba-1080-11e7-8104-bcb79b9de97d.png)

EDIT: Just discovered it works perfectly in Nuclide. Probably not very hard to fix please?

**Comment by thymikee** [comment]
I think this is a wontfix for now. These hints are TypeScript *parameter info* from [Intellisense](https://code.visualstudio.com/docs/editor/intellisense) and flow extension doesn't even touch them. They actually seem to work because of TypeScript syntax similarities

**Comment by mleg** [comment]
Thanks for your reply. That's surprising to know. Then it's probably a broader issue.
Hoping for reply from core developers about plans (if any) to address it.

**Comment by orta** [comment]
It's worth looking at [JavaScript Atom Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) to see if it fixes this 👍

**Comment by zhengying** [comment]
Any plan for this issue?
